package clg;

public class crop {
String str;
	public String fwheat(){
		str="Wheat is mainly a rabi (winter) season crop in India. Wheat is grown in a variety of soils of India.\n"
				+ " Soils with a clay loam or loam texture, good structure and moderate water holding capacity are ideal for wheat cultivation.\n"
				+ " Care should be taken to avoid very porous and excessively drained oils.\n"
				+ "Temperature: Between 10-15°C (Sowing time) and 21-26°C (Ripening & Harvesting) with bright sunlight.\n"
				+ "Rainfall: Around 75-100 cm.\n"
				+ "Soil Type: Well-drained fertile loamy and clayey loamy (Ganga-Satluj plains and black soil region of the Deccan)\n"
				+ " Classification of Indian Wheats:\n"
				+ "1. Emmer Wheat (Triticum dicoccum schub L.) :\n"
				+ "This type was reported to be grown in south i.e. Maharashtra, Tamil Nadu and Karnataka. This type is believed to be developed from T.\n"
				+ " diccoides koru., a wild form. It is also grown in Spain, Italy, Germany and Russia.\n"
				+ "2. Macroni Wheat ( T.durum Desf.) : The durum or macroni wheat, cultivation in India, is considered to be very old.\n"
				+ " It is a best wheat for drought conditions or under restricted irrigated conditions of Punjab, M.P.,\n"
				+ " Karnataka, Tamil Nadu, Gujarat, West Bengal and H.P. It is used for semolina (suji) preparation.\n"
				+ "3. Common Bread Wheat ( T. vulgare Host) :\n"
				+ "It is a typical wheat of alluvial soils of Indo-Gangetic plains i.e.Punjab, Uttar Pradesh, Bihar and parts of Rajasthan.\n"
				+ " The bulk of the Indian crop, therefore, consists of this type.\n"
				+ "4. Indian Dwarf Wheat (T.spherococcum Mihi.) :\n"
				+ "This belongs to the club wheat of western countries. This is found in limited areas of M.P., U.P., of India and in Pakistan. \n"
				+ "These are characterised by very short and compact heads having a shorter grains.\n"
				+ "5. Triticum aestivum :\n"
				+ "This is the type presently grown in India in almost all the wheat growing zones. It is used mainly for bread purpose.\n"
				+ " Land Preparation:\n"
				+ "The wheat crop requires a well-pulverized but compact seed bed for good and uniform germination.\n"
				+ " Three or four ploughings in the summer, repeated harrowing in the rainy season, followed by three or four \n"
				+ "cultivations and planking immediately before sowing produce a good, firm seed bed for the dry crop on alluvial soils. \n"
				+ "For the irrigated crop, the land is given a pre-sowing irrigation (palewa or raund) and the number of ploughings is reduced.\n"
				+ " Where white ants or other pests are a problem, Aldrin 5% or BHC 10% dust at the rate of 25 kg/ha should be applied to\n"
				+ "the soil after the last ploughing or before planking. \n"
				+ "a) Sowing time:"
				+ "Based on above temperature requirement it has been found that for indigenous wheat last \n"
				+ "week of October, for long duration dwarf varieties like Kalyansona, Arjun, etc. \n"
				+ "first fortnight of November and for short duration dwarf wheats like Sonalika, Raj 821 etc. \n"
				+ "second fortnight is the best sowing time. Under exceptionally late sown condition it may be delayed to \n"
				+ "latest by 1st week of December beyond which if area is very small transplanting may be practiced.\n"
				+ "b) Seed rate:"
				+ "Generally, a seed rate of 100 kg/ha has been found to be sufficient for most of the varieties\n"
				+ " like Kalyan Sona, Arjun, Janak, etc.which have moderate tillering and medium sized grains.\n"
				+ " But a higher seed rate of 125 kg/ha is desirable for late sown wheat and normal sown for varieties like Sonalika,\n"
				+ " Raj 821 etc. which have bold grains and shy tillering habits.\n"
				+ "c) Spacing: :"
				+ "For irrigated, timely sown wheat, a row spacing of 15 to 22.5 cm is followed,\n"
				+ " but 22.5 cm between the rows is considered to be the optimum spacing. Under irrigated late-sown conditions,\n"
				+ " a row spacing of 15-18 cm is the optimum. For dwarf wheats, the planting depth should be between 5 and 6 cm.\n"
				+ " Planting beyond this depth results in a poor stand. In the case of conventional tall varieties, the depth of sowing may be 8 or 9 cm.\n"
				+ "d) Seed treatment:"
				+ "The seed of loose smut-susceptible varieties should be given solar or hot-water treatment. \n"
				+ "If the wheat seed is used only for sowing, and not for human consumption or for feeding cattle, it can be treated with Vitavax.\n"
				+ " Fertilizer:With assured fertilizer supply:\n"
				+ "Nitrogen (N) @8- - 120 kg/ha "
				+ "Phosphorus (P2O5) @ 40- 60 kg/ha  "
				+ "Potash (K2O) @ 40 kg/ha.  "
				+ "Under fertilizer constraints:\n"
				+ "N @ 60-80 kg/ha  "
				+ "P2O5 @ 30-40 kg/ha   "
				+ "K2O @ 20-25 kg/ha";
		return str;
	}
public String fbarley() {
	String	st="Barley or Jau, scientifically known as Hordeum vulgare L. is one of the most important cereal\n"
				+ " crops in the world after rice, wheat and maize. Barley plant is a Rabi cereal crop from the\n"
				+ " grass family Poaceae. Barley crop is mostly found in cooler and semi-arid part of the world.\n"
				+ " It is believed that barley was originated in the Middle East. During the ancient time it was \n"
				+ "mainly grown for human consumption but nowadays barley production is also used for animal feed, malt products and human food.\n"
				+ "There are three main types of barley:\n"
				+ "Hordeum vulgare: This six -rowed barley variety bears a spike notched on opposite sides with \n"
				+ "three spikelets on each notch. Each notch carries a floret that later matures into a kernel.\n"
				+ " This variety of barley is the mostly cultivated variety across the world.\n"
				+ "Hordeum distichum: This two-rowed type of barley bears central florets which produce kernels. Its lateral florets are sterile.\n"
				+ "Hordeum irregulare: This variety is not cultivated for commercial purpose.\n"
				+ " It has fertile central florets and lateral florets could be sterile or fertile or both\n"
				+ "Climatic requirement: Barley can be grown as summer or winter crop.\n"
				+ " It can be successfully grown in tropical and subtropical climatic condition. The crop requires\n"
				+ " around 12-15°C temperature during growing period and around 30-32°C at maturity. The crop is extremely\n"
				+ " frost sensitive at any stage of growth. Any incidence of frost at flowering stage can result in huge yield loss.\n"
				+ " Barley crop is tolerant to drought and can survive in high temperatures.\n"
				+ "Soil requirement: Barley is mostly cultivated in sandy to moderately heavy loam soils. Therefore, \n"
				+ "soil of Indo-Gangetic plains having neutral to saline reaction and medium fertility are the most\n"
				+ " suitable soil types for barley cultivation. Barley crop can be cultivated in saline, sodic and lighter soils too. \n"
				+ "Soil acidity impairs the root growth of barley crop hence acidic soils are not suitable for barley cultivation.\n"
				+ "1Barley Seed Treatment\n"
				+ "Seed treatment is very important step before sowing. Proper seed treatment methodologies \n"
				+ "should be implemented to save the barley crop from termites, ants and other insect pests.\n"
				+ " Barley has very poor resistance to loose smuts. Treatment of loose smut disease can be performed\n"
				+ " with Vitavax or Bavistin @ 2 gm/kg seed. To control covered smut disease symptoms, mixture of Thiram \n"
				+ "+ Bavistin or Vitavax (1:1 ratio) @ 2.5 gm/kg seed is recommended Spacing for Barley Plant\r\n"
				+ "Row spacing for irrigated situation should be 22.5cm and 22.5 to 25 cm for rainfed situation.\n"
				+ " Depth of sowing must be 5cm under irrigated situation, whereas, in rainfed condition it should be 6- 8cm.Method of Sowing\n"
				+ "Seed drilling or seed dropping techniques are the best ways for seed sowing. \n"
				+ "Indian farmers mostly use Chonga for dropping seed to field which is attached to a desi plough.";
		return st;
	}
	public String fpeas() {
		String pe="Peas are small, round seeds that are inside the pods produced by the Pisum sativum plant.\n"
				+ " Pea belongs to the Leguminaceae group and is cultivated in the cool season. Pea is cultivated all around \n"
				+ "the world and in India, it can be found in the state of Himachal Pradesh, Madhya Pradesh, Rajasthan, West Bengal,\n"
				+ " Orissa and many more. The green ones are used as vegetables and the dry ones are used as pulses. \n"
				+ "Peas are a source of vitamins and minerals namely magnesium, thiamine, phosphorus etc. Green peas straw is good \n"
				+ "source of nutritional fodder for livestock. \n"
				+ "Climate requirement:  \n"
				+ "For pea cultivation, temperature should range between 15 degree to 30 degree Celsius. Optimum rainfall range is \n"
				+ "between 400 to 500 mm. While harvesting, the temperature should range between 15 to 20 degree Celsius and sowing \n"
				+ "temperature should range between 25 to 30 degree Celsius. \n"
				+ "Soil requirement: "
				+ "Cultivation can be done on several soil types. Well drained loam soil with a pH level of 6 to 7.5\n"
				+ " is optimum for farming of peas. Peas cultivation cannot thrive in water logged areas. Liming is to be done for acidic soil type. \n"
				+ "Major Varieties: \n"
				+ "Some of the major varieties include Early Bejar, Asauji, Jawahar Matar, Mithi Fali and Arket. \n"
				+ "Field arrangement: "
				+ "Once kharif crop harvest is done, a couple of ploughing along with harrowing is required. Once the ploughing\n"
				+ " and harrowing process is over, the hard clods are to be softened and proper leveling to be done in the field\n"
				+ " to avoid water logging problems. Before sowing of seeds, light showers of water is to be done for better germination.  \n"
				
				+ "Seed rate and treatment:"
				+ "A total of 35 to 40 kg of seed is to be used for 1 acre of land. \n"
				
				+ "1 kilo of seeds are to be treated with 3 grams of Captan or Thiram or 2.5 gram of Carbendazim. Once the chemical\n"
				+ " treatment is over, again treat the seeds with Rhizobium leguminosorum culture emulsified in ten percent of sugar solution.\n"
				+ " Thorough mixing has to be done with the seeds and should be kept in shade to dry. By doing so you can increase the total yield to\n"
				+ " more than 10 percent.  \n"
				
				+ "Seed sowing: \n"
				+ "Sowing has to be completed between the end of October and mid of November for plains and between mid of March till end of May\n"
				+ " for hills. Broadcasting method can be used for sowing seeds. Spacing wise 30 X 5 cm is maintained for early varieties and 50 X 10 cm \n"
				+ "for late varieties. Seeds are to be sown at a depth of 3 cm under the soil. \n"
			
				+ "Fertilizer requirements: \n"
				+ "Urea and SSP requirement per acre of land is 45 kilos and 155 kilos. And potash requirements will be on soil results. \n"
				
				+ "Nitrogen and Phosphorus requirement per acre of land is 20 kilos and 25 kilos.  \n"
				
				+ "While sowing, apply 20kg Nitrogen in form of 50kg Urea and 25kg Phosphorus in form of 150kg Superphosphate per acre. \n"
				+ "Provide dosage of fertilizer alongside the rows.";
		return pe;
	}
	public String fsugar() {
		String s="Sugarcane (Saccharum officinarum L.) is the main sources of sugar in India and holds a prominent position as a cash crop.\n"
				+ " India is the world’s largest consumer and the second largest producer of sugar, topped only by Brazil. Nearly 2.8 lakh farmers\n"
				+ " have been cultivating sugarcane in the vast area of 4.4 lakh acres and over 11 crore people are directly or indirectly dependent \n"
				+ "on the sugar industry in the country. Sugarcane is one of the important commercial crops of India, grown in an area of 3.93 m.ha with\n"
				+ " annual production of 170 M.T. Sugarcane productivity in India is around 67 t/ha. It is one of the most important food-cum-cash crop grown\n"
				+ " in the country, providing employment to a larger number of people, in addition to earning considerable foreign exchange.\r\n"
			
				+ "Requirement\n"
			
				+ "Climate"
				+ "Sugarcane is able to grow over a prolonged season. Under warm humid conditions, \n"
				+ "it can continue its growth, unless terminated by flowering. Temperatures above 50o C arrest its growth;\n"
				+ " those below 20 o C slow it down markedly and severe frost proves fatal. The crop does best in the tropical regions \n"
				+ "receiving a rainfall of 750-1200mm. For ripening, it needs a cool, dry season; but where rainfall is too heavy and prolonged, \n"
				+ "the quality of the juice tends to be low, and where the weather remains comparatively.\n"
			
				+ "Soil\n"
				+ "Sugarcane grows best on medium heavy soils, but can also be raised on lighter soils and heavy clays, \n"
				+ "provided there is adequate irrigation available in the former type of soils and drainage is good in the latter type of soils.\n"
				+ " In many places, dark rich clay loams, 120-150cm deep, and lying on a previous substratum of murum (distintegrated traprock) ae \n"
				+ "used for this crop. In some areas.\n"
				+ "Planting\\n"
				
				+ "Seed treatment"
				+ "The availability of good quality cane seed materials (setts) from a nursery crop of 10-11 months are essential\n"
				+ " for better germination and good growth. The treatments included were namely control, 0.05% Bavistin, 2.5% Urea, 2.5% KCI,\n"
				+ " 2.5% KCI+Urea, 1% Hadron. Two budded setts were used for planting after treating with above chemicals.\n"
				+ " Also hot water treatment is given to prevent seed borne diseases.\n"
			
				+ "Sowing\n"
				+ "Planting of sugarcane is done in three seasons that is suru- January-February, adsali - July-August and pre \n"
				+ "seasonal- October-November for planting generally ridges and furrows are prepared on 100-120cm spacing. For planting one hectare \n"
				+ "area 25-30 thousand three eye buded cane setts are required.\n"
				
				+ "Fertilizers\n"
				+ "Adequate manuring is essential for sustained high yields. The general recommendation in most places is to apply half to two-thirds\n"
				+ " of the nitrogen in the form of bulky organic manures, such as farmyard manure, compost, green manure or tree leaves, and the remainder\n"
				+ " in the form of ammonium sulphate or oil-cakes or a combination of the two. For sugarcane fertilizer is recommended according to planting \n"
				+ "season and it is varied from growing tract to tract. In general for suru sugarcane 250:115:115 for Adsali 400:170:170 and for pre \n"
				+ "seasonal 340:170:170 kg nitrogen, phosphorus and potash per hectare is recommended respectively. For ratooning 250:115:115kg nitrogen,\n"
				+ " phosphorus and potash per hectare is recommended.\n"
			
				+ "Irrigation\n"
				+ "Water requirement of sugarcane varies from 2000 to 2500 mm depending upon its duration, soil type and \n"
				+ "climatological factors. For sugarcane germination, tillering, grand growth and maturity are the critical stages\n"
				+ " for irrigation. During germination phase (1-35 days) there should be enough moisture in the soil for better germination \n"
				+ "but waterlogging is undesirable as it leads to rotting of setts. During this period irrigation can be scheduled at weekly intervals.\n"
				+ " But irrigation at 10 days interval during tillering stage (36-100 days) is sufficient. The formative and grand growth stages (101-270 days)\n"
				+ " are the critical stages for water demand.\n"
				
				+ "Harvesting and yield\n"
				+ "Assessing the maturity of the cane crop"
				+ "The maturity of sugarcane is generally recognized by the lower leaves\n"
				+ " gradually withering up and leaving progressively fewer green leaves at the top. A ripe cane, out across with a sharp knife,\n"
				+ " shows against sunlight a slight sparkling in its flesh in contrast to the more watery cut surface of an unripe cane. \n"
				+ "If the grower can keep and use a hand sugar refractometer, the testing of maturity would be easier. The hand refractometer\n"
				+ " reading of 20, the cane crop may be considered to have reached the stage of maturity. Small Mill Test (SMT) will be a real solution \n"
				+ "for this perennial problem. For conducting SMT, few canes (say about 10 canes) have to be cut from the field and the samples are \n"
				+ "analyzed after crushing the cane in a small mill for poll, brix, purity and ccs% in the laboratory which clearly gives the maturity \n"
				+ "status of the cane.";
		return s;
	}
	public String fmustard() {
		String m="Soil Requirement\n"
				+ "Light to heavy soil is good for mustard and rapeseed cultivation.\n"
				
				+ "Raya can be grown in all type of soil whereas loam to heavy soils are suitable for toria crop.\n"
				
				+ "Sandy and loamy sand soils are suitable for Taramira crops.\r\n"
				+ "Popular Mustard Varieties "
				+ "PBT 37 :\n"
				+ "Early maturity variety.\n"
				+ "Matures in 91 days."
				+ "It is suitable for toria-wheat cultivation."
				
				+ "Seeds are dark brown and bold in size."
				+ "It gives average yield of 5.4 qtl/acre and seeds contains 41.7% oil.\n"
				+ "TL 15 :"
				+ "It is early maturity variety."
				+ "It required 88 days to mature.\n"
				+ "TL 17 :"
				+ "Ready to harvest in 90 days."
				+ "Suitable for multiple cropping."
				+ "It gives average yield of 5.2 qtl/acre.\n"
				+ "mustard "
				+ "Land Preparation"
				+ "Fine seed beds are required for good germination of crop.\n"
			+ "Ploughing of soil should be done for two to three times followed by two harrowing."
				+ "Planking should be done after every ploughing.\n"
				+ "Prepared firm, moist and uniform seed bed as it will help in uniform germination of seed.\n"
				
				+ "Sowing\r\n"
		
				+ "Time for sowing Mustard crop is from September to October month.\r\n"
				+ "For toria crop, sowing from first fortnight of September to October."
				+ "For African sarson and Taramira can be sown in whole October month.\n"
				+ "For Raya crop complete sowing from Mid of October to November End.\n"
				+ "Spacing "
				+ "For rapeseed :- Row to Row distance of 30 cm and plant to plant distance of 10-15 cm.\n"
				+ "For Gobhi sarson :- Row to Row distance of 45 cm and plant to plant distance of 10 cm.\r\n"
				+ "Depth "
				+ "Depth should be kept at 4 to 5 cm.Seed Rate."
				+ "Rapeseed :- seed rate of 1.5 kg seeds per acre.\n"
				+ "Thinning operations must be done three week after sowing and maintain only healthy seedlings.\r\n"
				+ "Seed Treatment \n"
				+ "Before sowing do seed treatment with Thiram at 3gm per kg of seeds.\n"
				+ "Fertilizer Requirement (kg/acre)\n"
				+ "Crop      UREA     SSP         MURIATE OF POTASH\n"
				+ "Toria      55           50           On soil test results\n"
				+ "Weed Control in Mustard"
				+ "Weed control in Toria crop, do pre-plant incorporation of Trifluralin at 400ml/200Ltrs of water per acre.\r\n"
				+ "For raya crop, give pre-emergence spray of Isoproturon at 400gm/200Ltr within 2 days of sowing.\r\n"
				+ "Irrigation\r\n"
				+ "Pre-sowing irrigation should be done before sowing of seeds.\r\n"
				+ "For getting good growth, crop required in general about three irrigation apply at interval of three weeks after sowing.\r\n"
				+ "Good amount of organic manures should be applied in the soil, it will help to conserved moisture in soil.\r\n"
				+ "Harvesting\r\n"
				+ "Depending variety crop takes 110 to 140 days to mature.\r\n"
				+ "When you see pods turn yellow and seed become hard then harvest crop.\r\n"
				+ "Carry out harvesting in morning hours to avoid shattering loss .\r\n"
				+ "Cut crops close to ground with the help of sickle.\r\n"
				+ "Stacked the harvested crops for 7-10 days.\r\n"
				+ "Complete threshing operation after proper drying";
		return m;
	}
	public String frice() {
		String rice="Rice is the most important food crop of India covering about one-fourth of the total cropped area \r\n"
				+ "and providing food to about half of the Indian population.Conditions of Growth:\r\n"
				+ "Rice is grown under varying conditions in India from 8° to 25° N latitude and from sea level \r\n"
				+ "to about 2,500 metre altitude. It is a tropical plant and requires high heat and high humidity\r\n"
				+ " for its successful growth. The temperature should be fairly high at mean monthly of 24°C. It \r\n"
				+ "should be 20°- 22°C at the time of sowing, 23°-25°C during growth and 25°-30°CIt is the dominant \r\n"
				+ "crop in areas of over 200 cm annual rainfall and is still an important crop in areas of 100-200 cm\r\n"
				+ " rainfall. The 100 cm isohyet forms the limit of rice in rainfed areas. In areas receiving less \r\n"
				+ "than 100 cm annual rainfall, rice can be grown with the help of irrigation, as is done in Punjab,\r\n"
				+ " Haryana and western U.P. About 40 per cent of rice crop in India is raised under irrigation.\r\n"
				+ "However, it is the temporal distribution of rainfall, rather than the total amount of \r\n"
				+ "annual rainfall which is more decisive. The rainfall should be fairly distributed throughout \r\n"
				+ "\\the year and no month should have less than 12 cm of rainfall. \r\n"
				+ "Lesser amount of rainfall is required as the harvesting time approaches.\r\n"
				+ "The fields must be flooded under 10-12 cm deep water at the time of sowing and during early stages of growth.\r\n"
				+ " Therefore, the fields must be level and have low mud walls to retain water. \r\n"
				+ "This peculiar requirement of rice makes it primarily a crop of plain areas. Rice grown in well watered lowland plain areas is called wet\r\n"
				+ " or lowland rice."
				+ "In hilly areas, the hill slopes are cut into terraces for the cultivation of rice. \r\n"
				+ "Such a cultivation in which the hill slopes are cut into terraces is called terraced cultivation. \r\n"
				+ "The supply of water to the hill terraces is not as much as in the plain areas and the rice grown \r\n"
				+ "in hilly areas is called dry or upland riceMethods of Rice Cultivation:\r\n"
				+ "Following methods of rice cultivation are practised in India.\r\n"
				+ "1. Broadcasting method:"
				+ "Seeds are sown broadcast by hand. This method is practised in those areas which are comparatively dry and less fertile\r\n"
				+ " and do not have much labour to work in the fields. It is the easiest method requiring minimum input but its yields are also minimum.\r\n"
				+ "2. Drilling method:"
				+ "Ploughing of land and sowing of seeds is done by two persons. This method is mostly confined to peninsular India.\r\n"
				+ "3. Transplantation method:This method is practised in areas of fertile soil, abundant rainfall and plentiful supply\r\n"
				+ " of labour. To begin with, seeds are sown in nursery and seedlings are prepared. After 4-5 weeks the seedlings are \r\n"
				+ "uprooted and planted in the field which has already been prepared for the purpose. The entire process is done by hand.\r\n"
				+ " It is, therefore, a very difficult method and requires heavy inputs. But at the same time it gives some of the highest yields.";
		return rice;
	}
	public String maize() {
		String maize="Maize is one of the important foods, green forage & industrial crops of the world."
				+ " It is called QUEEN OF THE CEREALS. Maize has highest yield/ha among the cereal crops. \r\n"
				+ "\r\n"
				+ "Climate:\r\n"
				+ "\r\n"
				+ "Maize is a tropical plant which prefers warm humid weather. It is a short-day plant. It is very sensitive to excess"
				+ " or deficit soil moisture. It cannot with stand frost at any stage of growth. The optimum pH range of soil for maize"
				+ " is 6.5-7.5. 600 mm rainfall with even distribution is sufficient for good cultivation. Optimum temperatures for germination are "
				+ "21 c and for growth is 3 c respectively. \r\n"
				+ "\r\n"
				+ "Soils: \r\n"
				+ "Maize can be grown on a variety of soils, but it grows best on well drained soils. \r\n"
				+ "\r\n"
				+ "1. Best soils- Deep dark silt loams\r\n"
				+ "\r\n"
				+ "2. In semi-arid climates- Deep soils (Heavy Texture)\r\n"
				+ "\r\n"
				+ "3. In sub humid climates- Sand Loam soils\r\n"
				+ "\r\n"
				+ "Seasons: \r\n"
				+ "Kharif – sowing in between last week of May to 2nd week of June and harvested in late September or October. \r\n"
				+ "\r\n"
				+ "Varieties:  \r\n"
				+ "1. DHM-101,103, 1 Rohini, Ashwini]- Synthetics\r\n"
				+ "\r\n"
				+ "2. Trishulatha-3 Way cross\r\n"
				+ "\r\n"
				+ "3. Arsha & Varun- Composites\r\n"
				+ "\r\n"
				+ "Land preparation:\r\n"
				+ "2-3 shallow tillage operations during summer season are essential. Deep ploughing is also helpful to control weeds & for efficient moisture conservation\r\n"
				+ "Seed Rate:  \r\n"
				+ "1. For pure crop: 20-25 kg/ha\r\n"
				+ "\r\n"
				+ "2. For fodder maize: 40-50 kg/ha\r\n"
				+ "\r\n"
				+ "3. For intercropping with soybean: 10kg/ha (1:3) or 15 kg/ha (1:2)\r\n"
				+ "\r\n"
				+ "Spacing: \r\n"
				+ "60×25cm or 75×20cm \r\n"
				+ "\r\n"
				+ "But crop geometry of 45×20cm is found to be optimum for most of the areas.  \r\n"
				+ "\r\n"
				+ "Method of sowing:\r\n"
				+ "Dibble the seed 2-3cm deep & should not be more than 5cm. \r\n"
				+ "\r\n"
				+ "Weed Management: \r\n"
				+ "Maize needs two inter-cultivations & two hand-weeding’s. First inter-cultivation is done between rows near to plants for earthing up. Second inter-cultivation should not be done near the plants nor deep.  \r\n"
				+ "\r\n"
				+ "The combined use of herbicides & inter-cultivations is the most effective technique of weed control in maize. \r\n"
				+ "\r\n"
				+ "Pre-emergence –Simazine (Tafazine) or Atrazine (Atrafaf) @ 2kg/ha should be sprayed 2 or 3 DAS (Days after sowing), by wetting the entire surface uniformly. Later the soil should not be disturbed for 4-5 weeks after application of the herbicide.\r\n"
				+ "\r\n"
				+ "Post-emergence—2,4 DEE at 1 ½ - 2 kg/ha at any time when maize is about 20cm height.\r\n"
				+ "\r\n"
				+ "Water Management: \r\n"
				+ "The optimum available soil moisture for maize crop is 75% or 80%. \r\n"
				+ "\r\n"
				+ "The frequency of irrigation will be once in 6-10 days depending upon rainfall. The total water requirement varies from 530mm to 800mm depending upon season & rainfall received during the crop growth crop period. \r\n"
				+ "\r\n"
				+ "Light & frequent irrigations just to moisten the effective root zone of the maize crop viz., 15cm to 22.5cm depth of soil are more conductive to higher yield. \r\n"
				+ "\r\n"
				+ "Up to 40 DAS, the crop is more sensitive to excess moisture & from pre-flowering to maturity, it is more sensitive to drought. \r\n"
				+ "Harvesting:\r\n"
				+ "Hybrids of maize mature within 90-110 days. Plants may remain green when cobs are dry & ready for harvest. Therefore, do not wait for stalks to dry up for harvesting, this is desirable as such plants can be used as fodder. \r\n"
				+ "Test for Maturity:\r\n"
				+ "The husk cover turns pale brown & the grains are too hard to be pressed in with finger nail.";
		return maize;
	}
	public  String fjowar() {
		String j="Sorghum (Jowar) is grown on a variety of soil types but the clayey loam soil rich in humus is found to be the most ideal soil. It may tolerate mild "
				+ "acidity to mild salinity under pH 5.5 to 8.0. A good Sorghum (Jowar) soil must have an efficient drainage facilities though, it may withstand water "
				+ "logging more than maize.\r\n"
				+ "\r\n"
				+ "Season and Area of Cultivation\r\n"
				+ "Sorghum (Jowar)is mainly concentrated in the peninsular and central India.\r\n"
				+ "Land Preparation:\r\n"
				+ "Deep summer ploughing with mould board plough soon after rabi crop is harvested and leaving the soil exposed to sun until onset of monsoon is a"
				+ " common practice. With the onset of monsoon the land should be ploughed twice by country plough. But the soil for grain crop should be pulverised for "
				+ "a fine tilth by harrowing and cross plankings. If desired, field should be levelled before sowing so that rainwater may be well distributed throughout "
				+ "the field.a) Sowing time:Sorghum crop is grown in almost all the seasons of the year. In Northern India conditions it is grown in kharif season but in"
				+ " Southern India the crop is grown during Rabi and summer seasons. Kharif crop should be sown soon after first break of monsoon rains i.e. nearly "
				+ "in last week of June. Therefore, the best sowing time is in last week of June to first week of July depending upon onset of monsoon. Whereas rabi jawar"
				+ " is sown in the month of October to November.\r\n"
				+ "\r\n"
				+ "b) Spacing:A spacing of 40-45 cm between the rows and 15-20 cm between the plants is quite satisfactory.\r\n"
				+ "\r\n"
				+ "c) Seed rate: Required plant population may be obtained by using a seed rate of 8-12 kg/ha. The seeds are sown about 3-4 cm deep in the furrows.\r\n"
				+ "\r\n"
				+ "Seed treatment:\r\n"
				+ "The seed treatment may be done by Agrosan GN, Thiram at the rate of 3g/kg of seed or sulphur at the rate of 5g/kg of seed. The seed is treated"
				+ ", dried and sown in the field.Sorghum is a fairly drought resistant crop and it does very well in areas receiving 50 cm well distributed rainfall "
				+ "but it cannot withstand waterlogging at any stage of crop growth. The most critical growth stages for irrigation are knee-height stage, flowering and grain filling stages at which the crop should be ensured for proper moisture conditions so that the crop does not suffer from moisture stress.Contrary to this in kharif crop an efficient drainage must be provided as the crop cannot tolerate water accumulation for more than few hours, therefore, in low lying areas sowing of crop on 5-7cm high ridges or sowing in flat beds followed by light earthing is a remedy for stagnant water in the field.a) Harvesting\r\n"
				+ "The high yielding varieties mature in about 100-120 days duration after which they are harvested. Generally two methods of harvesting i.e. either"
				+ " stalk-cut or cutting of earheads by sickles are employed. However, in foreign countries sorghum harvesters are used. In case of stock cut method "
				+ "the plants are cut from near the ground level, the stalks are tied into bundles of convenient removed from plants, while in later case the earheads,"
				+ " after their removal from the standing crop, are piled up on the threshing floor and after few days they are threshed. Threshing of earheds is done"
				+ " either by beating them with sticks or by trampling them under bullock’s feet. Later method is quicker and is practiced by majority of farmers who use"
				+ " to grow the crop on larger scale. ";
		return j;
	}
	public  String fbajra() {
		String b=" Climate and soil:\r\n"
				+ "The crop has a wide adaptability as it may grow under different day lengths, temperature and moisture stress. Most of the varieties developed in India "
				+ "are photosensitive which helps in growing the crop during monsoon, rabi and arid season. It requires low annual rainfall ranging between 40-50 cm and"
				+ " dry weather. The crop may tolerate drought but cannot withstand high rainfall of 90 cm or above. Light soils of low inherent fertility good drainage,"
				+ " mild salinity are best type for this crop. Crop does not tolerate soil acidity\r\n"
				+ "Land preparation:\r\n"
				+ "The crop needs very fine tilt because the seeds are too small. 2-3 harrowings and a ploughing is followed so that a fine tilth may be obtained to"
				+ " facilitate the sowing and proper distribution of seed at appropriate depth.\r\n"
				+ "\r\n"
				+ "Varieties:\r\n"
				+ "NBH-149, VBH-4 developed for Andhra Pradesh, Madhya Pradesh, Gujarat, Maharashtra are capable of producing 14% higher yield.\r\n"
				+ "ICM4-155 gave higher yield than the standard check and adopted for all growing tracts of India.Also H-306, NH-338 and hybrid like MP-204, MP205 have"
				+ " been identified.\r\n"
				+ "\r\n"
				+ "Sowing\r\n"
				+ "Sowing time :- Most appropriate time of sowing is middle or last week of July\r\n"
				+ "Seed rate and Spacing:-\r\n"
				+ "4-5 kg/ha for drilling method\r\n"
				+ "2.5-3 kg/ha for dibbling method\r\n"
				+ "spacing 40 –45 cm between rows, 10 –15 cm within rows.\r\n"
				+ "Seed treatment- The organo-mercurial compound Ceresan, Agrosan should be used @ 2.5-3 kg/ha to control seed borne diseases\r\n"
				+ "\r\n"
				+ "Generally the crop requires low quantity of nutrients. But All India Co-ordinated Millet Improvement Project has proved that new plant types of bajra"
				+ " especially hybrids respond to very high doses of fertilizers.\r\n"
				+ "\r\n"
				+ "Under rainfed areas application of organic manures such as FYM or compost helps in increasing the crop yield at the rate of 150-200 quintals/ha 80 –100"
				+ " kg N:40-50 kgP:40-50kgK is recommended dose for hybrid variety.\r\n"
				+ "\r\n"
				+ "Fertilizers are applied in split doses, half of nitrogen, full phosphorus and potash should be basal placed at the time of sowing . The organic manures"
				+ " must be applied 20 days before the sowing of the seeds for full decomposition. One fourth dose of nitrogen should be applied about 30 days and 60 days "
				+ "after sowing.\r\n"
				+ "\r\n"
				+ "Interculture\r\n"
				+ "Thinning or gap filling is followed at the time of first interculture. Hand weeding is followed to control the weeds or application of Atrazine @ 0.5"
				+ " kg/ha would take care of most of the weeds.\r\n"
				+ "\r\n"
				+ "Irrigation:\r\n"
				+ "Bajra is grown rainfed and crop being drought resistant hardly needs any irrigation, however it is observed that the yield may be significantly "
				+ ""
				+ "increased by irrigating the crop at critical growth stages like maximum tillering, flowering and grain filling stage. Therefore light irrigations and"
				+ " efficient drainage is very essential for bajra production.\r\n"
				+ "Harvesting and threshing:\r\n"
				+ "The crop is harvested when grains become hard enough and contain moisture. Two methods are adopted for harvesting the crop Cutting earhead\r\n"
				+ "i) from standing crop followed by cutting of remaining plants later\r\n"
				+ "ii) Cutting of entire plants by sticks and stalking the plants for five days in sun for obtaining grains. Grains are separated either by"
				+ " beating the earheads with sticks or by trampling the earheads under bullock feet";
		return b;
	}
	public  String fmoong() {
		String m=" Green gram (Phaseolus aureus Roxb) is important pulse crops. The grains (whole or split) are used as a pulse or made into flour, and into"
				+ " straw and husk as fodder for cattle. Grains are also eaten whole (after germinating them), parched, salted, with sugar or boiled with condiments. "
				+ "The important states producing this pulse are Madhya Pradesh, Maharashtra, Uttar Pradesh, Punjab and Andhra Pradesh, Rajasthan, Karnataka and Tamil"
				+ " Nadu.\r\n"
				+ "\r\n"
				+ "Requirement\r\n"
				+ "Climate\r\n"
				+ "The crop needs a well-distributed rainfall. Heavy rains at flowering are harmful, even moist winds at this stage interfere with fertilization.\r\n"
				+ "\r\n"
				+ "SoilThis pulse does best on deep, well-drained loams in the alluvial tract in the north as well as on the red and black soils of peninsular and "
				+ "southern India. It is also cultivated on light or shallow stony soils to clayey soils.\r\n"
				+ "\r\n"
				+ "Varieties\r\n"
				+ "'T 1, 'T 44', 'Pusa Baisakhi', 'PS 7', 'PS 16,' 'S 8','S 9', 'Varsha (H70-16)' Hissar, ' G 65', ' Jawahar 45',' Kopergaon', ' ML 1','Ml 5',' ML 9'\r\n"
				+ "\r\n"
				+ "Cultivation\r\n"
				+ "For the pure crop in the kharif season, the land is ploughed once or twice and harrowed to obtain a rough tilth. The summer crop can be sown dry in"
				+ " furrows in between the rows of the previous crop, followed by irrigation.\r\n"
				+ "\r\n"
				+ "Sowing\r\n"
				+ "The kharif crop is sown in June to July, and the rabi crop in September or October. The spring crop is to be sown by 15 February and harvested by"
				+ " the middle of May. The summer crop is sown by 15 April. The seed may be sown by broadcasting or it may be drilled in furrows behind a plough, or "
				+ "with a three-or four-coultered desi drill, in rows 20-30cm apart. The seed-rate varies from 15-20kg per hectare when sown alone and for mixed crop"
				+ " 2-6kg per hectare.\r\n"
				+ "\r\n"
				+ "Fertilizer\r\n"
				+ "Manuring with 25-40kg per ha of phosphorus (P2O5) and 25kg per ha of nitrogen (N) should be given at the time sowing. Also seed treatment with "
				+ "biofertilizer viz. Rhizobium at the rate of 25gram per kg of seed is beneficial.\r\n"
				+ "\r\n"
				+ "Irrigation\r\n"
				+ "Being kharif crop green gram is not required irrigation unless there is dry spell during the kharif season. In summer irrigation should be given"
				+ " according to soil type. Irrigation interval should be 8-10 days in summer. Flowering and pod filling are the critical stages for irrigation.\r\n"
				+ "\r\n"
				+ "Plant protection\r\n"
				+ "Pest\r\n"
				+ "1. Aphids\r\n"
				+ "The nymphs and adults suck the sap. The affected leaves turns yellow, get wrinkled and distorted. The insect also exude honeydew on which fungus "
				+ "develops, rapidly covers the plant with sooty mould that interferes with the photosynthetic activity of the plant.\r\n"
				+ "Control\r\n"
				+ "Spraying with 0.05% Endosulfan, 0.02% Phosphamidon, 0.03% Dimethoate, Methyl demeton or Thiometon control the pest effectively.\r\n"
				+ "\r\n"
				+ "2. Thrips\r\n"
				+ "The adults and nymphs feed on leaves. They scrape the epidermis and such the oozing sap. As a result, light brown patches appear on infested leaves."
				+ " The affected leaves curl and become dry.\r\n"
				+ "ControlSpraying with 0.05% Endosulfan, 0.02% Phosphamidon, 0.03% Dimethoate, Methyl demeton or Thiometon control the pest effectively.\r\n"
				+ "\r\n"
				+ "3. Pod borer\r\n"
				+ "Caterpillars feed on tender foliage and young pods. They make holes in the pods and feed on developing seeds by inserting anterior half portion of"
				+ " their body inside the pods.\r\n"
				+ "Control\r\n"
				+ "In early stage of attack handpicking of the caterpillars and their destruction. Ploughing fields after the harvest of crop would expose the pupae,"
				+ " which would be destroyed by birds. Spraying the crop with 0.05% Quinalphos or Fenitrohion can successfully control the pest. Spray with HaNPV @ "
				+ "250 LE/ha.\r\n"
				+ "Disease\r\n"
				+ "1. Leaf spot\r\n"
				+ "Angular brown or red spots, with grey or brown centre and reddish-purple border on leave, stalk and pods\r\n"
				+ "Control\r\n"
				+ "Spray with Bordeaux mixture (5:5:50) or 0.2% Ziram.\r\n"
				+ "\r\n"
				+ "2. Powdery mildew\r\n"
				+ "White powdery patches on leaves and other green parts, later becoming dull coloured and are studded with black dot.\r\n"
				+ "Control\r\n"
				+ "Dust the crop with finely powdered sulphur (200-mesh) @ 20kg/ha.\r\n"
				+ "\r\n"
				+ "Harvesting and yield\r\n"
				+ "To avoid loss because of the shattering of pods, the crop is harvested before it is dead ripe. One or two rounds of the picking of pods are"
				+ " also recommended to avoid losses because of the shattering. The plants are uprooted or cut with a sickle, are dried on the threshing-floor for"
				+ " a week or ten days and threshed by beating with sticks, and are winnowed with baskets. The average yield of grain from a pure crop varieties from"
				+ " 5-6q per ha, whereas yields up to 10-15q per ha.";
		return m;
	}
	public  String furad() {
		String b=" Land Preparation For Black Gram Cultivation\r\n"
				+ "\r\n"
				+ "If you want to plan for black gram cultivation then first of all the land preparations are very needful. The selected land must not be sown "
				+ "the black gram in a previous year. You are planning to start cultivation in Kharif season then plowed the selected land in summer by using two "
				+ "or three harrowing. Before sowing a seed in field remove the extra weed and stone from the land. Apply 5 to 6-tonne compost or farm yard manure "
				+ "before sowing black gram. You can also provide the irrigation if it is required before sowing the seeds.\r\n"
				+ "\r\n"
				+ "Seed Selection And Treatment In Black Gram Cultivation\r\n"
				+ "\r\n"
				+ "The selection of seed plays the most important role for the successful black gram cultivation. When you select the seed for black gram cultivation "
				+ "then must care the selected seeds should be free from the pest, insect, diseases, dust particles and weed. Seed should be well growing and clean. "
				+ "Generally, prefer to purchase seeds from the Agril, research station, Agril service centers, Agriclinics and registered seed companies.\r\n"
				+ "\r\n"
				+ "First, apply 2.5-gram thiram on one kg black gram seeds. Also, treat this selected seeds with rhizobium and atmospheric nitrogen.\r\n"
				+ "\r\n"
				+ "Black Gram Sowing Season And Method\r\n"
				+ "\r\n"
				+ "The appropriate time for sowing black gram seeds for Kharif season is the 15 to 30 of June. If you are planning for the summer black gram crop then"
				+ " the February third week to April first week is better for the sowing seeds.\r\n"
				+ "\r\n"
				+ "There are basically two methods are available for the sowing seed and this both method can be done by using the tractor or Bullock Ferti-cum-seed"
				+ " drill.\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "Line sowing method\r\n"
				+ "Drilling sowing method\r\n"
				+ "You can use this Ferti-cum-seed drill for applying the fertilizers and sowing seed at the same time. The maximum depth of the sown seed must be "
				+ "5 to 6 cm.\r\n"
				+ "\r\n"
				+ "Black Gram Seed Rate And Space\r\n"
				+ "\r\n"
				+ "The price of the black gram seeds is relying on the variety of seed.\r\n"
				+ "\r\n"
				+ "SEASON SEED RATE SPACING\r\n"
				+ "Kharif 12 to 15 kg / ha 30 X 10 cm\r\n"
				+ "Summer 20 to 25 kg / ha 20-25 X 10 cm\r\n"
				+ "\r\n"
				+ "Fertilizer For Black Gram Cultivation\r\n"
				+ "\r\n"
				+ "In the following table, you will see the require fertilizer amount for black gram depending on the soil test report. You can apply this "
				+ "fertilizer on a field after 25 to 35 days of seed sowing and the second time after 40 to 50 days.\r\n"
				+ "\r\n"
				+ "SR. NO. NPK DOSE (KG/HA) FERTILIZER (KG/HA) TIME OF APPLICATION\r\n"
				+ "1. 20 kg N 44 kg Urea Basal application at the of sowing with ferti-cum-seed drill\r\n"
				+ "2. 40 kg P 250 kg SSP Basal application at the of sowing with ferti-cum-seed drill\r\n"
				+ "3. 40 kg K 67 kg MOP Basal application at the of sowing with ferti-cum-seed drill\r\n"
				+ "\r\n"
				+ "Irrigation Required For Black Gram Cultivation\r\n"
				+ "\r\n"
				+ "There are many irrigation systems are available in latest technology like drip irrigation, sprinkler irrigation, micro jet, and basin irrigation but"
				+ " suitable irrigation for the black gram cultivation are depending on the weather condition and soil type.\r\n"
				+ "\r\n"
				+ "Black gram cultivation only requires irrigation in a summer season. It does not require irrigation in rainy seasons. The black gram plant requires"
				+ " irrigation in the interval of 10 to 15 days. Black gram plant needed a moisture in the soil during the flowering to pod phase.";
		return b;
	}public  String fjute() {
		String m="Jute is a rainy season crop, sown from March to May according to rainfall and type of land.  It is harvested from June to September depending "
				+ "upon whether the sowings are early or late.\r\n"
				+ "\r\n"
				+ "Climate and Soils  \r\n"
				+ "Jute requires a warm and humid climate with temperature between 24° C to 37° C.  Constant rain or water-logging is harmful.  The new gray alluvial "
				+ "soil of good depth, receiving salt from annual floods, is best for jute.  Flow ever jute is grown widely in sandy loams and clay loams.\r\n"
				+ "\r\n"
				+ "Sowing of jute \r\n"
				+ "Sowing of jute in midlands and high lands starts with showers in March or April and continues till early June in the western part of the jute belt. "
				+ " Compost or firm yard manure, Phosphorus and Potash, Nitrogen fertilizers are used as a fertilizer.  Interculturing is essential in the early stage."
				+ "  Pasts are also require for plant protection. \r\n"
				+ "\r\n"
				+ "Introduction\r\n"
				+ "Statistics\r\n"
				+ "Cultivation\r\n"
				+ "	\r\n"
				+ "Gradation\r\n"
				+ "Manufacturing\r\n"
				+ "Basic Products\r\n"
				+ "Testing\r\n"
				+ "Harvesting \r\n"
				+ "Jute is harvested any time between 120 days to 150 days when the flowers have been shed, early harvesting gives good healthy fibers.   The plant "
				+ "from 8 to 12 feet high are cut with stickles at or close the ground level.  In flooded land, plants are up rooted.  The harvested plants are "
				+ "left in field for 3 days for the leaves to shed.\r\n"
				+ "The stems are then made up into bundles for steeping in water.  Steeping is carried out immediately after harvest.\r\n"
				
				+ "\r\n"
				+ "The Fibre Extraction \r\n"
				+ "The jute plant's fibres  lie beneath the bark and   surrounded the woody central part of the stem.  To extract the fibres from the stem, the process"
				+ " is carried out in the following stages :\r\n"
				+ "\r\n"
				+ "Retting \r\n"
				+ "Retting is a process in which the tied bundles of jute stalks are taken to the tank by which fibres get loosened and separated from the woody stalk."
				+ "  The bundles are steeped in water at least 60 cm to 100 cm depth.  The retting process is completed in 8 to 30 days, when the barks separate out "
				+ "easily from the stick or wood and the fibres are ready for extraction.  A development in recent years is adoption of ribbon retting technology in "
				+ "jute growing trade of the country.\r\n"
				+ "\r\n"
				+ "Stripping (Fibre Extraction) \r\n"
				+ "Stripping is the process of removing the fibres from the stalk after the completion of retting.  Fibres are removed from the stalk by any one of "
				+ "the following \r\n"
				+ "methods  :  \r\n"
				+ "  (i)      Single plants are taken and their fibers are taken off. \r\n"
				+ "  (ii)     Taken off a handful of stalks,breaking it in a to and fro motion in water.  \r\n"
				+ " (iii)     Washing the stalks first by standing in waist deep water and then stripping afterwards.\r\n"
				+ "\r\n"
				+ "When there is a plenty of water, bundles of stalks are laid in the pond ditches or slow moving streams and left for 5-15 days under water.  "
				+ "The bunch of stem is held in one hand and the root end tapped lightly with a mallet.  After loosens the rest of fibres, fibres are extracted and "
				+ "washed.\r\n"
				+ "\r\n"
				+ "Washing and Drying\r\n"
				+ "Extracted fibres are washed in clean water.  The dark colour of fibres can be removed by dipping them in tamarind water for 15 to 20 minutes and "
				+ "again washed in clean water.  After squeezing excess water the fibres are hang on bamboo railing for sun drying for 2-3 days.\r\n"
				+ "Bailing and Packing\r\n"
				+ "The jute fibre is graded into tops, middles, B, C and X-bottoms.  Packing into Kutcha bales about 250 pounds for use in the home trade."
				+ "  they are transported to jute market or direct to jute mills. ";
		return m;
	}
	public  String fgr() {
		String b=" Introduction:\r\n"
				+ "Groundnut (Arachis hypogaea L.) is important oilseed crop and oil content of the seed varies from 44-50%, depending on the varieties"
				+ " and agronomic conditions. It is also used in soap making, and in manufacturing cosmetics and lubricants, olein, stearin and their salts."
				+ " Kernels are also eaten raw, roasted or sweetened. They are rich in protein and vitamins A, B and members of the B2 group."
				+ " The cake can be used for manufacturing artificial fibre. The haulms are fed (green, dried or silaged) to livestock. Groundnut shell is used as fuel"
				+ " for manufacturing coarse boards, cork substitutes etc. Groundnut is also of value as a rotation crop. The production are concentrated in the four states "
				+ "of Gujarat, Andhra Pradesh, Tamil Nadu and Karnataka. Andhra Pradesh, Tamil Nadu, Karnataka and Orissa have irrigated areas.\r\n"
				+ "\r\n"
				+ "Requirement\r\n"
				+ "Climate\r\n"
				+ "The crop can be grown successfully in places receiving a minimum rainfall of 500mm and a maximum rainfall of 1,250mm. The rainfall should be "
				+ "distributed well during the flowering and pegging of the crop. The groundnut cannot stand frost, long and severe drought or water stagnation.\r\n"
				+ "\r\n"
				+ "Soil\r\n"
				+ "The crop does best on sandy loam and loamy soils and in black soils with good drainage. Heavy and stiff clays are unsuitable for groundnut cultivation "
				+ "as the pod development is hampered in these soils.\r\n"
				+ "\r\n"
				+ "Varieties\r\n"
				+ "Bunch type\r\n"
				+ "'Junagadh-II', 'TMV-2', 'Pol-2', 'AK 12-24', 'Kopergaon-3', 'KG-61-240' (Jyothi).\r\n"
				+ "\r\n"
				+ "Semi-spreading type\r\n"
				+ "'TMV-6', 'TMV-8','Kopergaon-1', 'C-501'.\r\n"
				+ "\r\n"
				+ "Spreading type\r\n"
				+ "'Punjab-I', 'GAUG-10','Kadiri-71.1', TMV-1', 'TMV-3', 'S-230', 'Karad4-11'\r\n"
				+ "\r\n"
				+ "Cultivation\r\n"
				+ "For a kharif crop, with the onset of rains in May-June, the field is given two ploughing and the soil is pulverized well to obtain a good tilth."
				+ " Harrows or tiller can be used for cultivation. If a field is infested with white grubs, chemicals, such as Heptachlor or Chlordane, are drilled at"
				+ " the rate of 25kg per ha. before final harrowing. For the irrigated crop, beds of convenient size may be made, depending upon the topography of the land,"
				+ " the nature of the irrigation source and the mode of lifting water.\r\n"
				+ "\r\n"
				+ "Sowing\r\n"
				+ "Groundnut is raised mostly as a rainfed kharif crop, being sown from May to June, depending on the monsoon rains. It is sown as late as August or early"
				+ " September. As an irrigated crop it is grown to limited extent between January and March and between in May and July. Well-filled kernels should be selected"
				+ " and treated with 5g of Thiram or 3g of Captan per kg of kernels. The quantity of well-developed seeds required per hectare about 110 kg for semi spreading "
				+ "and spreading varieties and 120kg for the bunch varieties. The kharif crop is sown with a seed drill or with a suitable planter at a depth of 8-10 cm. for"
				+ " semi spreading and spreading varieties, the spacing between at he adjacent rows varies for m30-60cm and within the row from 10-15cm. For the rainfed bunch"
				+ " groundnut the inter-row spacing vary between 20 and 30cm and the intra-row spacing between 10 and 20cm.\r\n"
				+ "\r\n"
				+ "Fertilizer\r\n"
				+ "Fertilizer recommended for rainfed crop is 6.25 tonnes farmyard manure and 10-25kg nitrogen (N), 20-40kg phosphorus (P2O5) and 20-40kg potash (K2O) per "
				+ "hectare. For irrigated crop 12.5 tonnes farmyard manure and 20-40kg nitrogen (N), 40-90kg phosphorus (P2O5) and 20-40kg potash (K2O) per hectare. "
				+ "The application of nitrogen (N) in two equal splits doses, one before sowing and the other 30 days after sowing. The application of a culture of Rhizobium"
				+ " as seed treatment is beneficial in increasing nodulation and nitrogen fixation. The application of gypsum at 500kg per ha at the pegging stage will enhance"
				+ " pod formation.\r\n"
				+ "\r\n"
				+ "Irrigation\r\n"
				+ "The kharif crop is caught in a long spell of drought, especially at the pod-formation stage, supplemental irrigation is given. For the irrigated groundnut,"
				+ " the frequency of irrigation depends on the soil texture, and the interval between irrigation ranges from 8-12 days. The peg-formation stage is critical.\r\n"
				+ "\r\n"
				+ "Intercultural operations\r\n"
				+ "For controlling weeds, and also to keep the soil in a friable condition, the crop should generally receive a hand-weeding and one or two hoeings, "
				+ "with bullock-drawn implements, the first about three weeks after sowing and the second and the third about a fortnight and a month later. No interculture"
				+ " would be done after the pegs have commenced going underground. Earthing up can be done in the case of bunch and semi-spreading types for facilitate the "
				+ "maximum penetration of the pegs into the soil. Weeds can also be controlled effectively with Lasso or Tok-E-25 weedicide at the rate of 5 litres in 500"
				+ " litres of water per hectare as a pre-emergence soil spray within two days of sowing groundnut.\r\n"
				+ "\r\n"
				+ "Plant protection\r\n"
				+ "Pest Leaf-miner\r\n"
				+ "Caterpillars mine the tender leaves and later fold the adjacent leaves to feed within. Pest active during July to December; drought, with occasional "
				+ "showers favourable.\r\n"
				+ "\r\n"
				+ "Control\r\n"
				+ "Dust 4% Carbaryl,\r\n"
				+ "\r\n"
				+ "Groundnut aphid\r\n"
				+ "Vector of a virus disease (rosette), dry and warm weather, favourable.\r\n"
				+ "\r\n"
				+ "Control\r\n"
				+ "Spray 0.03% Dimethoate or Phosphamidon, Monocroptophos or Methyl-demeton\r\n"
				+ "\r\n"
				+ "White grub\r\n"
				+ "The adults emerge immediately after the monsoon; grubs feed on roots and kill the plants.\r\n"
				+ "\r\n"
				+ "Control\r\n"
				+ "Grubs very difficult to kill; the application of 10% Phorate granules is to be effective.\r\n"
				+ "\r\n"
				+ "Disease\r\n"
				+ "Root rot\r\n"
				+ "Reddish brown discolouration on the stem, spreading and the plant collapsing; tissues blackened and numerous tiny black scleriotia are formed\r\n"
				+ "\r\n"
				+ "Control\r\n"
				+ "Practise crop rotation, treat seed with Agrosan GN or Ceresan or Thiram @ 3gram per kg of seed.\r\n"
				+ "\r\n"
				+ "Tikka disease or leaf spot\r\n"
				+ "Dark spots surrounded by a bright-yellow ring on the leaves and sometimes on the petiole and the stem; premature leaf-shedding is characteristic.\r\n"
				+ "\r\n"
				+ "Control\r\n"
				+ "Spray with Brestan or with 4:4:50 Bordeaux mixture or with 0.2% Ziram or Zineb or Maneb.\r\n"
				+ "\r\n"
				+ "Bunchy top\r\n"
				+ "Leaves reduced in size and malformed; suppression of the internodes; partial sterility.\r\n"
				+ "\r\n"
				+ "Control\r\n"
				+ "Use well-developed disease free seeds, rogue out diseased plants.\r\n"
				+ "\r\n"
				+ "Harvesting and yield\r\n"
				+ "The prominent symptoms of maturity are the yellowing of leaves, the shedding of the older leaves, the development of the proper colour of the testa and "
				+ "a dark tint inside the shell. The bunch and semi-spreading varieties are usually harvested by hand pulling when there is adequate moisture in the soil. "
				+ "The spreading types, on the other hand, are harvested by digging or by ploughing or working a blade harrow. The pulled out plants are stacked for a few "
				+ "days for drying and are stripped afterwards.";
		return b;
	}public  String fso() {
		String m=" Climate-\r\n"
				+ "Soyabean needs about 15 to 320C temperature for germination but for rapid growth the crop needs higher temperature."
				+ " The crop requires about 60-65 cm annual rainfall drought at flowering or just before flowering results in flower and pod drops, "
				+ "while rains during maturity impairs the grain quality of soyabean. harmful. The best soil type is sandy loam having good organic matter content.\r\n"
				+ "\r\n"
				+ "Soyabean - Crop Cultivation Guidence\r\n"
				+ "Varieties\r\n"
				+ "Monetta, M.A.C.S.-13, M.A.C.S.-57, M.A.C.S.-58, M.A.C.S-124, P.K. 472, J.S.-80-21, J.S. 335\r\n"
				+ "\r\n"
				+ "Sowing\r\n"
				+ "Two cropping seasons of soybean Kharif and spring.\r\n"
				+ "In case of Kharif season most common time of sowing is onset of monsoon or last week of June to first week of Jully while spring"
				+ " sowing is done between 15th of February and 15th of March.\r\n"
				+ "\r\n"
				+ "Method of sowing - Line sowing by seed drill followed as it needs less seeds/ha, weeding and hoeing may be done conveniently\r\n"
				+ "\r\n"
				+ "Seed treatment- Seeds are treated with rhizobium culture.\r\n"
				+ "\r\n"
				+ "Spacing- A 45-60 cm X 2.5 cm spacing is good for Kharif crop and 30-45 X 2.5 cm during spring season.\r\n"
				+ "\r\n"
				+ "Seedling depth- 2-3 cm in heavy soils and 3-4 cm light soils.\r\n"
				+ "\r\n"
				+ "Seed rate- Soyabean grown for grain purpose needs about 20-30 kg seed/ha but for fodder crop needs about 70-75 kg/ha during Kharif season"
				+ " and 100-120 kg/ha during spring.\r\n"
				+ "\r\n"
				+ "\r\n"
				+ " \r\n"
				+ "Fertilizers-\r\n"
				+ "Soyabean gives higher positive response to applied nitrogen over symbiotically fixed atmospheric nitrogen through its roots alone which proves"
				+ " that nitrogen fixed by soyabean roots is not enough for its and development. Crop is supplied with 10-15% of total nitrogen requirement\r\n"
				+ "\r\n"
				+ "Application of 25-30 C.L.FYM at the time of sowing proved better results.50 Kg N + 100 Kg P2O5, 20 kg sulphur per ha. Also 25 Kg Zinc sulphate"
				+ " and 10 Kg Borax should be applied.\r\n"
				+ "\r\n"
				+ "Water requirement\r\n"
				+ "In case of Kharif crop irrigation is not needed and it is grown rainfed. However during summer the crop can be grown only under assured"
				+ " irrigation and it needs about 5-6 irrigations. The crop should be irrigated at the following critical growth stages to minimize water.\r\n"
				+ "1. Sprouting stage\r\n"
				+ "2. Flowering pod initiation and bean filling stages are important from yield point of view\r\n"
				+ "\r\n"
				+ "Cultivation Practices\r\n"
				+ "At the time of sowing one deep ploughing two harrowings should be given tomaintain optimum moisture at sowing.\r\n"
				+ "\r\n"
				+ "After care\r\n"
				+ "Keep plot weed free upto 40 days by one or two hoeings, two weedings upto 40 days. Herbicides such as Toke 25, 1.5 to 2 Kg/ha"
				+ " pre-emergence before sowing controls the weeds.\r\n"
				+ "\r\n"
				+ "Crop Rotation and inter cropping\r\n"
				+ "Mixed with maize, sesamum etc. Inter cropping with Tur, Cotton, drilled paddy sorghum, cotton, sugarcane. It can be rotated"
				+ " with wheat, potato, gram, tobacco\r\n"
				+ "\r\n"
				+ "Harvesting\r\n"
				+ "Crop harvested at proper stage by usual method, threshing machine.\r\n"
				+ "Signs of maturity- Dropping of leaves, leaves turn yellow, moisture content of seed 15%";
		return m;
	}
	public String veg() {
		String ve=" ";
		return ve;
	}
	public String fru() {
		String fr=" ";
		return fr;
	}public String flo() {
		String fl="";
		return fl;
	}
	
}
