package clg;

public class fal {
public String orange() {
	String or="Climate Condition For Orange Farming\r\n"
			+ "Where do oranges grow? Likewise Mango Farming and Banana Farming, Oranges are also cultivated widely as they can grow well in the tropical region as well as in sub-tropical regions up to a height of 1500 m. However, a dry climatic condition is favorable for profitable orange cultivation for obtaining higher oranges production.\r\n"
			+ "\r\n"
			+ "Orange farming\r\n"
			+ "\r\n"
			+ "A soil temp. (about room temp: 26 ‘C) is beneficial in enhancing the growth of plant root as well plant growth. However, farming oranges in an arid and drier area with good hot summer and moderate rainfall, about 100 to 200 cm is considered as the best and most favorable climatic conditions for the excellent growth of orange plants.\r\n"
			+ "\r\n"
			+ "Take care that orange trees are very sensitive to high humid and frost condition and such climatic condition in orange farming invites numbers of many diseases and harmful pest, insect, etc. Also, note that hot winds during summer lead to dropping down of orange flower and budding fruits. So, for obtaining high production of oranges, it is a good idea to keep maintaining the favorable temp in your farm during the growth period.\r\n"
			+ "\r\n"
			+ "Soil Requirement for Orange Farming\r\n"
			+ "Oranges can be cultivated on a wide variety of soil like sandy loam to loamy soil, alluvial, red to black soils with too much clay. However, a soil with high fertility, good drainage power, lime-free soil with good salt absorption power and light loam is considered as the best & most favorable for the orange cultivation.\r\n"
			+ "\r\n"
			+ "As soil ph for citrus trees is about 6.0 to 7.0 and oranges are also a citrus tree, it is smartness to cultivate them on soil, which has pH ranging between 5. 8 to 7.3 for best production.Spacing\r\n"
			+ "Prepare a pit, having size 80 cm X 80 cm X 80 cm. Add about 10 kg of rotten cow dung manure to the topsoil of the pit. Plant the Oranges, keeping a distance of 7 meters between the rows and 7 meters apart. However, the spacing in orange cultivation depends on the type of soil, method and the cultivars, selected for the cultivation.Orange Harvesting\r\n"
			+ "Generally, An orange plant becomes mature at the age of one year. After which they start flowering and budding, but not in proper amount or less no. of fruit are obtained in the first harvesting.\r\n"
			+ "\r\n"
			+ "Usually, Depending on the types of orange cultivated, from the 4th year onward, you will be able to harvesting oranges. And an orange tree used to give fruit for about 25 yrs in an economic life. Collect those tasty and delicious oranges at three different intervals, during a year. Harvest them in autumn, summer, and in the rainy season. ";
	return or;
}
public String banana() {
	String b=" Climate: Being a tropical crop, banana requires warm, humid and rainy climate. The optimum temperature range is 10 to 400C and the relative humidity is 90% or above. It is highly susceptible to frost and cannot tolerate arid conditions. Strong desiccating winds cause considerable reduction in the growth of the plant and yield and quality of fruits.\r\n"
			+ "\r\n"
			+ "Soil: Banana is a heavy feeder crop/. Therefore, fertility of soil is very important. Rich, well drained, fertile, free working, soils with plenty of organic matter are best suited for cultivation. The optimum range of pH of soil should be 6 to 8.\r\n"
			+ "\r\n"
			+ "Propagation: Commercial edible bananas do not produce viable seeds. So, the banana is commonly propagated by suckers and sword suckers with narrow leaves. Rhizomes whole or in bits from fruited and non-fruited plants with atleast one sound bud can be successfully used as propagating material.\r\n"
			+ "\r\n"
			+ "Planting: Planting of banana is done by two methods viz. Pit method and furrow method. Planting is done from February to May whereas in North India, it is done during July-August. In South-India, it can be done any time of year except summer. Tall varieties should be planted at 3x3 m whereas dwarf ones at 2x2 m apart.\r\n"
			+ "\r\n"
			+ "Manuaring: Banana is a heavy feeder and responds well to manuring. Banana is a quick growing and short-lived plant. Therefore, it is more beneficial, if quick growing fertilizers are applied. In Tamil Nadu, application of 100 g of N, 30 g of P2O5 and 300 g of K2O per plant to be supplied in three doses during the second, third and fifth months is recommended. In Maharashtra, 100 g N, 40 g P2O5 and 100 g K2O per plant is recommended. Out of these, P2O5 and K2O is applied at the time of planting and N is given is three split doses: third, fourth and fifth month after planting.\r\n"
			+ "\r\n"
			+ "After Cares:\r\n"
			+ "\r\n"
			+ "Desuckering: - Desuckering is an important operation in banana cultivation. In this, the unwanted suckers, which develop near the base of the plant, are removed. Cutting the suckers from ground level and then pouring the kerosene (2-3 drops) to kill the growing point of pseudostem does it.\r\n"
			+ "\r\n"
			+ "Propping: - It is an essential cultural practice to give proper support to the plants with bamboos. It is done to avoid falling down of plants due to high winds.\r\n"
			+ "\r\n"
			+ "Wrapping: - to protect the fruits from sunburn, hot wind and dust the bunch is covered. Wrapping is also done to improve the colour of the fruit.\r\n"
			+ "\r\n"
			+ "Harvesting and Yield: Harvesting of banana is done 12 to 15 months after planting in dwarf and 15 to 18 months after planting in tall varieties. Signs of maturity of banana fruits are, fruit becomes plumpy and angles are filled in completely, when tapped gives metallic sound, drying off of top leaves and change in colour of fruits from deep green to light green.\r\n"
			+ "\r\n"
			+ "Tall varieties like Poovan yield 15-25 tonnes/ha, while Dwarf Cavenshish yield 25-50 tonnes/ha. It can be stored at temperature slightly above 550F and relative humidity of about 85-95% for about three weeks.";
	return b;
}
public String chiku() {
	String c=" Climate: The Sapota is a tropical fruit crop and can be grown from Sea level upto 1200 m. height. It prefers a warm and humid weather and grows in both dry and humid areas. Areas with an annual rainfall of 125-250 cm are highly suitable. The optimum temperatures ranges between 12 deg.cent. to 36 deg.Cent.\r\n"
			+ "\r\n"
			+ "Soil requirement: The Sapota tree is a hardy perennial and evergreen tree and can be grown on a wide range of soils. Drainage is most important. There should not be a hard pan in the sub-soil. Deep and porous soils make a good growth. The Sapota can tolerate the presence of salts in the soil or in irrigation water to some extent.\r\n"
			+ "\r\n"
			+ "Varieties: The important and widely adopted varieties are Kali Patli and Cricket Ball ( Calcutta Large). The other varieties are, pili patti, Bangalore, Baramati, Dwarapudi, Chhatri, etc.\r\n"
			+ "\r\n"
			+ "Propagation: The Sapota can be propagated by seeds by grafting or by layering. However, commercially followed method is softwood grafting on rayan seedlings. This method has replaced the earlier method called as approach grafting. The Sapato when grafted on rayon has initially slow growth but the tree lasts longer. The layered plants grow vigorously and the method is cheaper as no root stock is required.\r\n"
			+ "\r\n"
			+ "Planting and Season: The planting of grafts is done from June to October, for which pits of 1x1x1 m at the distance of 8 x 8 or 9 x 9 or 10 x 10 m are dug well before the onset of monsoon. The pits are filled in with a well decomposed manure, 5:10:5 mixture, single super phosphate, neem cake and a mixture of micronutrients. Hundred to 120 plants are accommodated in a hectare.\r\n"
			+ "\r\n"
			+ "Interculturing: The Sapota has a long pre-bearing age and a wider spacing allows enough interspace for growing certain crops for few seasons. The short duration fruit crops like banana, papaya, pineapple or vegetables, different types of lillies or groundnut, chilli, gram,etc. are suitably grown for some seasons. Frequent weeding or mulching is necessary for first few years.\r\n"
			+ "\r\n"
			+ "Care of young orchard: A strong windbreak should be established by planting tall and thick growing trees on the windward or on all the sides of the orchard. Frequent removal of outgrowth on the stock is necessary in grafting plants. Gap filling and supporting with bamboo is to be done as early as possible. Young plants are likely to damaged due to the scorching sun, dry and hot wind and frost. Necessary protective are adopted.";
	return c;
}
public String mosambi() {
	String m=" SOIL\r\n"
			+ "It can be grown on wide variety of soils. Medium-Light Loam soils with pH of 6.0-8.0 are suitable for its best growthLAND PREPARATION\r\n"
			+ "Land need to be prepare properly for growing seedlings. Land should be ploughed, Cross ploughed and leveled. Terrace planting is done on hills. High density planting is possible in hilly areas.\r\n"
			+ "\r\n"
			+ "Show Less\r\n"
			+ "SOWING\r\n"
			+ "Time Of Sowing\r\n"
			+ "In Punjab planting is done in Spring season (February to March) and Monsoon season (15 August to October end).\r\n"
			+ "\r\n"
			+ "Spacing\r\n"
			+ "For sweet oranges use spacing of 5mx5m is recommended. Dig pit of 1mx1mx1m, kept open in sun for some days. Add 15-20kg of well decomposed cow dung, SSP@500gm per Pit.\r\n"
			+ "\r\n"
			+ "Sowing Depth\r\n"
			+ "Pits of size 60×60×60cm should be dug for planting seedlings.\r\n"
			+ "\r\n"
			+ "Method Of Sowing\r\n"
			+ "\r\n"
			+ "Propagation\r\n"
			+ "Root stock raising: Sow citrus seeds in nursery on bed of 2mx1m size and with 15cm distance between the row. When seedlings are of 10-12cm height, transplanting is to be done. Select healthy and uniform size seedling for transplantation purpose. Remove dwarf and weak seedlings. If needed, pruned roots slightly before planting. In nursery, Budding is done when plant are of pencil thickness. Shield budding or T shape budding is done for that, T shaped slot is made in bark of tree at distance of 15-20cm from ground. Horizontal cut of about 1.5-2cm long is given, and vertical cut of 2.5cm long is made from middle of horizontal cut. Remove bud from bud stick and insert it into T shape slots, afterward wrapped it with plastic paper.   \r\n"
			+ "T budding is done during February-March and also in August- September. Propagation in sweet orange, kinnow, grape fruit is done by T budding while for lime and Lemon, it is propagated by Air layering method.HARVESTING\r\n"
			+ "On attaining proper size, shape along with attractive color having TSS to Acid ratio of 12:1, kinnow fruits is ready for harvest. Depending upon variety fruits are generally ready for harvesting in Mid- January to Mid- February. Do harvesting at proper time as too early or too late harvesting will give poor quality.";
	return m;
	
}
public String custard() {
	String a="Climate: all annonas are tropical in origin and grow well in hot and dry climate with varying degrees of difference. Custard Apple requires hot dry climate during flowering and high humidity at fruit setting. Flowering comes during hot dry climate of May but fruit setting takes place on onset of monsoon. Low humidity is harmful for pollination and fertilization. The Custard Apple withstands drought conditions cloudy weather and also when the temperatures go below 15 deg.cent. Annual rainfall of 50-80 cm is optimum, though it can withstand higher rainfall.\r\n"
			+ "\r\n"
			+ "Soil: The Custard Apple is not very particular about soil conditions and flourishes in all types of soils like shallow, sandy, but fails to grow if the subsoil is ill drained. It can grow well in deep black soils provided they are well drained. A little salinity or acidity does not affect it but alkalinity, chlorine, poor drainage or marshy-wet lands hamper the growth and fruiting.\r\n"
			+ "\r\n"
			+ "Varieties: The following are some of the varieties grown in different agro-climatic regions of the country.\r\n"
			+ "\r\n"
			+ "Red Sitaphal\r\n"
			+ "\r\n"
			+ "Balanagar\r\n"
			+ "\r\n"
			+ "Hybrid\r\n"
			+ "\r\n"
			+ "Washington\r\n"
			+ "\r\n"
			+ "Purandhar (Pune)\r\n"
			+ "\r\n"
			+ "Propagation: The annonas are commonly propagated by seeds. Recently some researchers have developed some techniques in vegetative methods and budding can be adopted for multiplication. The seedlings of local custard apple have proved a good root stock for many improved varieties and hybrids. Seeds treated with 100 ppm for 24 hours germinate quickly and uniformly.\r\n"
			+ "\r\n"
			+ "Planting and Season: Planting is done during rainy season. The pits of 60x60x60 cm at spacing 4x4 or 5x5 or 6x6 depending on soil type are dug prior to monsoon and filled with a good quality FYM, single super phosphate and neem or Karanj cake under dry conditions and with drip irrigation system planting at 6x4 meters has given good growth and better fruit setting.\r\n"
			+ "\r\n"
			+ "Interculturing: For good plant growth, the weeding should be done to keep away the weeds. Intercropping with some legumes, peas, beans and merigold flowers are commonly taken by the growers. Normally, no crop is taken during winter as the plants go under rest.\r\n"
			+ "\r\n"
			+ "Care of young orchard: The gap filling is to be done as early as possible. Stagnation of water during first monsoon should be taken care of, if the planting is done on imprevious soils or ill drained soils.\r\n"
			+ "\r\n"
			+ "Special horticultural practices: For uniform flowering and for early flowering and also to check the flower and fruit drop and for improving fruit size, following growth regulators are used.\r\n"
			+ "\r\n"
			+ "For defoliation and bringing the plants under uniform rest Ethryl at 1000 ppm is sprayed one month after the harvest of the fruits.\r\n"
			+ "\r\n"
			+ "For better and early flowering Biocil a ml per litre of water is sprayed just prior to flowering.\r\n"
			+ "\r\n"
			+ "10 to 20 ppm NAA is sprayed just prior to flowering period to reduce the flower and fruitdrop.\r\n"
			+ "\r\n"
			+ "During fruit development 50 ppm GA + 5 ppm + 0.5 ppm cppu, foliar spray improves the fruit size and luster of the fruits.\r\n"
			+ "\r\n"
			+ "Irrigation: In general, Custard apple is grown as a rainfed crop, and no irrigation given. However, for early and bumper harvest of the crop. Irrigation on flowering i.e. from May should be given till regular monsoon starts. For better flowering and fruit setting, mist sprinkling is better over flood or drip system of irrigation as it keeps to lower down the temperatures and to increase in the relative humidity.\r\n"
			+ "\r\n"
			+ "Nutrition: Generally, no manures or fertilizers are applied to rainfed crop. However, for early and bumper harvest with a good keeping quality, the following dose is recommended to a fully grown tree. Biomeal …. 10 kg, 5:10:5 1 Kg. Ormichem micronutrient mixture 0.250 kg at the time of flowering and another dose of 10:26:26 or 19: 19: 19 mixture after fruit setting. Foliar spray with 8:12:24:4 10 gm/lt, twice during fruit development. Occassionally, zinc or iron or both deficiencies are noticed and can be taken care of by spraying chealed zinc or Ferrous.\r\n"
			+ "\r\n"
			+ "Plant protection: Though the crop is hardy, it suffers from the following pests-\r\n"
			+ "\r\n"
			+ "Mealy bug\r\n"
			+ "\r\n"
			+ "Scale insects\r\n"
			+ "\r\n"
			+ "Fruit boring caterpillar\r\n"
			+ "\r\n"
			+ "Leaf spot, Anthrac nose, Black stone, spraying with neem oil, Meenark, and some herbal preparation is recommended.\r\n"
			+ "\r\n"
			+ "Harvesting and yield: The Custard apple is a climacteric fruit and harvested at the maturity state when the fruit starts to change colour from green to its varietal colour shade. Immature fruits do not ripe. Swallowing some apical buds – showing inner pulp is also an indication of maturity. A were grown tree yield above 100 fruits weighing 300 to 400 gm. The season of harvest is from August to October. ";
	return a;
}
public String guava() {
	String g=" Climate and Soil:\r\n"
			+ "\r\n"
			+ "The guava is grown widely in tropical and sub-tropical regions and succeeds under a wide variety of climatic conditions. It favours distinct winters and tolerates high rainfall and drought conditions. Fruit setting and fruit development are poor if the temperatures are high and humidity is low.\r\n"
			+ "\r\n"
			+ "The guava is grown on heavy clay soils to very right sandy soils as well as on those, which are commonly considered suitable for fruit production. The trees are hardy and can stand the high E.C. and pH. However, well drained condition is necessary for survival and production.\r\n"
			+ "\r\n"
			+ "Varieties\r\n"
			+ "The important cultivars (varieties) are as under: -\r\n"
			+ "Sardar (Lucknow-4a)\r\n"
			+ "Allahabad Safeda\r\n"
			+ "Banarasi Surkha\r\n"
			+ "Apple colour\r\n"
			+ "Red fleshed\r\n"
			+ "Chittidar\r\n"
			+ "Seedless\r\n"
			+ "Out of these first two are grown on large scale.\r\n"
			+ "\r\n"
			+ "Propagation\r\n"
			+ "The guava is propagated by seeds, grafts, airlayers and ground layers. The method, ground layering is easy, economical and followed on large scale. Use of 3000 to 5000 ppm or a mixture of IBA and IAA has been found very effective in early and profuse rooting.\r\n"
			+ "\r\n"
			+ "Planting and Season:\r\n"
			+ "The guava can be planted at any time of the year. However, June planting followed by January planting is more successful and very well adopted.\r\n"
			+ "\r\n"
			+ "A spacing of 7x7 or 6x6 sq.m.is recommended and the pits of 0.75x0.75x0.75 or 1x1x1 m are dug at the selected spacing and filled with organic manures, superphosphates and neem cakes well grown layers, uniform in rooting and short growth are used for planting.\r\n"
			+ "\r\n"
			+ "Interculturing:\r\n"
			+ "During initial period of 2/3 years from planting, interspace is kept weed free by regular weeding. Short duration crops, preferably vegetables are taken.\r\n"
			+ "\r\n"
			+ "Care of young orchard\r\n"
			+ "Gap filling should be done within a month.\r\n"
			+ "Supporting and training to young trees is necessary to get uniform stand of all the plants.\r\n"
			+ "Necessary provision for wind breaks is useful. Plants like susbenia, Mulberry, etc. is done at the planting of main crop.\r\n"
			+ "Special Horticultural Treatments\r\n"
			+ "Training and pruning : The guava plants are trained to a single stem. No branching is allowed upto the height of 1 m on main trunk. Pruning to young plants is necessary to have uniform and well balanced growth and shape. Judicious pruning is also recommended prior to flowering of selected bahar. Pruning increase the productivity and makes the various operations like spraying, harvesting easy.\r\n"
			+ "\r\n"
			+ "Bahar treatment: This consists of withholding of water prior to flowering of bahar. Normally there are three bahars i.e. Mrig bahar, Hast bahar and Amba bahar, out of which only one is selected depending on climate and market. Root pruning and shoot pruning are also followed as a supporting treatments at bahar treatment.\r\n"
			+ "\r\n"
			+ "Bending of branches: This practice is only followed in certain erect growing types to improve flowering.\r\n"
			+ "\r\n"
			+ "Irrigation\r\n"
			+ "Flood irrigation, the trees are regularly irrigated during the fruiting season – from flowering to harvest of the crop. Excess of water adversely affects the quality of the fruits besides it favours excessive vegetative growth and invites fungal diseases. Drip irrigation and fertilization are the latest techniques, which economise the use of water and fertilisers. However, during the vegetative growth period moisture is necessary and the system should be on as per requirements.\r\n"
			+ "\r\n"
			+ "Application of manures and fertilisers\r\n"
			+ "\r\n"
			+ "The amount of fertilisers and manures depend on soil, variety, yield potential and age of the tree. The guava responses well to organise and biofertilisers and balanced NPK. Many times deficiencies of Mg, Z & Mn are seen which can be rectified by spraying with cheleted micronutrients or micronutrients mixtures. The fertilizers schedule is modified by adopting periodical soil and tissue analysis data. Well grown trees require 360g nitrogen, 180g phosphorus and potash/tree/year, in addition to 60 to 100kg of organic matter. Excess of chemical N should be avoided to get a good quality.\r\n"
			+ "\r\n"
			+ "Plant protection\r\n"
			+ "\r\n"
			+ "The important pests are – Fruitfly, scale insect, Bark eating caterpillars, Mealy bug and important diseases are – Fruit canker, Anthracnose, leaf spot, wilt, fruit and rot. Proper training, optimum pruning, favourable selection of bahar, clean cultivation, adopting preventative measures and timely sprays are followed to protect the crop from diseases and pests. Integrated pest management is always better than only chemical control.\r\n"
			+ "\r\n"
			+ "Harvesting and yields\r\n"
			+ "\r\n"
			+ "The vegetatively grown plants start bearing at 3rd year and continue to give economic yields yearly for 30 years. The well grown and well cared trees gives annual yield from 100 to 150kg. The fruits should be harvested at full maturity but in semiripe conditions.\r\n"
			+ "\r\n"
			+ "Post harvest management, storage and marketing\r\n"
			+ "\r\n"
			+ "The fruits are highly perishable and should be marketed within two days of harvest. Over ripe fruits will not stand a long distance market. Some hormones like Mh, GA have been reported to increase self life of fruits. The fruits can be stored for four weeks in cold storage maintaining the temperatures 8 to 100C and relative humidity 80-90%";
	return g;
}
}
