package clg;

public class fer extends sfertilizer{

	public String Nitrogen() {
	String nt="Nitrogen fertilizer is an essential resource for agriculture, and its use has undoubtedly benefited California and its citizens. Nitrogen is necessary for crop growth and development, and thus nitrogen fertilizer use supports California’s robust agricultural economy.\r\n"
			+ "\r\n"
			+ "Overuse of nitrogen fertilizer threatens the health of the state’s agriculture. It is worth noting that fertilizer is just one way humans add reactive nitrogen into the environment, and other activities such as fossil fuel combustion and waste discharge contribute to the aforementioned concerns.\r\n"
			+ "\r\n"
			+ "Inorganic nitrogen fertilizer use is responsible for the largest fraction, by far, of new nitrogen introduced into California’s environment each year. The amount of inorganic (chemical) nitrogen fertilizer sold in California has risen dramatically over the past 70 years.\r\n"
			+ "\r\n"
			+ "Intergovernmental Panel on Climate Change (IPCC) suggests that estimated application of nitrogen fertilizer to cropland is a key parameter to use in approximating cropland emissions of nitrous oxide, a potent greenhouse gas.\r\n"
			+ "\r\n"
			+ "There are no easy solutions to managing the trade-offs associated with agricultural nitrogen; this is due to\r\n"
			+ "1. The complexity of the nitrogen cycle in general and\r\n"
			+ "2. The mobility and diversity of soil nitrogen compounds in particular.\r\n"
			+ "\r\n"
			+ "The vast majority of nitrogen in soils is in soil organic matter and hence does not pose an immediate threat to the environment or humans. This soil organic matter serves as a nitrogen reservoir, and each year a fraction of this nitrogen is mineralized to ammonium.\r\n"
			+ "Source: https://ucanr.edu\r\n"
			+ "\r\n"
			+ "Nitrogen Fertilizers and Soil Reactions\r\n"
			+ "Mineralization\r\n"
			+ "\r\n"
			+ "The microbial transformation of organic nitrogen to inorganic forms is referred to as mineralization. Common organic nitrogen substances are; soil humus, plant leaf clippings and root tissue, and sludge and manure based fertilizers. Generally, a complex and large molecule containing nitrogen is broken down into a simpler and smaller molecule and then into ammonium. Sometimes this process is referred to in two parts with the first part termed aminization and the second part ammonification.\r\n"
			+ "\r\n"
			+ "Many different types of organisms can perform these reactions, some can do both steps while others can only perform one reaction or the other. Fungi and bacteria carry on most of the mineralization in soils. Because many different organisms can mineralize nitrogen in the conditions necessary for mineralization to occur are not highly specific. Warm, wet conditions, and soil pH greater than 5.5 enhance mineralization. Good soil aeration promotes mineralization, so water contents greater than field capacity tends to reduce the rate of nitrogen mineralization. One factor that can be altered by the turfgrass manager and greatly affects how fast nitrogen is released from an organic nitrogen source is the C: N ratio of the material.\r\n"
			+ "\r\n"
			+ "Carbon: Nitrogen ratio\r\n"
			+ "\r\n"
			+ "The rapidness of nitrogen mineralization from organic compounds is a function of the carbon:nitrogen ratio (C:N) of the material. In substances with low C:N ratio, less than 15:1, the nitrogen content is relatively high and the microorganisms rapidly release nitrogen when they decompose the material. On the other hand, if the C:N ratio of the material is high (greater than 30:1), indicating a low nitrogen content, then mineralization is slow. In order for the organisms to break down a high C:N material inorganic nitrogen is removed from the soil solution. This process is called immobilization and occurs frequently when high C:N substances (for example: sawdust, some compost, types of sludge) are added to soil. If the material has a high enough C:N ratio all of the inorganic nitrogen can be removed from the soil for a considerable amount of time. The growth of grass plants will then be halted. Microorganisms are much more competitive for soil nitrogen then plants so they consume the inorganic nitrogen first before the plants.\r\n"
			+ "\r\n"
			+ "Fumigation can eliminate mineralization\r\n"
			+ "\r\n"
			+ "The microbial populations necessary for mineralization to occur are essentially eliminated by fumigation for a period of time. Therefore, organic nitrogen sources will not be made available to the plant by mineralization to inorganic nitrogen forms. Only inorganic nitrogen sources will be successful in providing the grass with nitrogen shortly after fumigation. Mineralization will eventually take place after some time that is determined by the thoroughness of the fumigation and the movement of organisms from adjacent areas into the fumigated areas.\r\n"
			+ "\r\n"
			+ "Nitrification\r\n"
			+ "\r\n"
			+ "Nitrification refers to the conversion of ammonium to nitrate. This conversion is a two step reaction performed by two distinct and specific microorganisms. The first step is the conversion of ammonium to nitrite by Nitrosomonas and the second step is the conversion of nitrite to nitrate by Nitrobacter. Luckily this reaction is tightly coupled so that nitrite in soils rarely accumulates.\r\n"
			+ "\r\n"
			+ "Nitrite is highly toxic to plants.\r\n"
			+ "\r\n"
			+ "Since only two microorganisms are involved in this reaction the conditions that alter the reaction rate are relatively narrow and well understood.\r\n"
			+ "\r\n"
			+ "Temperature\r\n"
			+ "\r\n"
			+ "Nitrification occurs in soils at temperatures above freezing. The warmer the temperature the faster the rate of nitrification. For example: ammonium sulfate was mixed with soil and kept moist at different temperatures for 24 days. At 40 of, 29% of the ammonium had been nitrified, at 60 of, 59% was nitrified, and at 80 of, 100% was converted to nitrate. Thus temperature has a substantial effect on the form of nitrogen available to the turfgrass plant. Fertilization with an ammonium source in cool weather may supply substantial amounts of ammonium to the plant, but at high temperatures most of the nitrogen available to the plant will be nitrate.\r\n"
			+ "\r\n"
			+ "Soil pH\r\n"
			+ "\r\n"
			+ "Nitrification occurs in soils at pHs between 5.5 and 10. The optimum pH is around 7. ";
	return nt;
	}
	public String pho() {
		String ph="The function of phosphorus in plants is very important.\n"
				+ " It helps a plant convert other nutrients into usable building blocks with which to grow.\n"
				+ " Phosphorus is one of the main three nutrients most commonly found in fertilizers and is the “P” in \n"
				+ "the NPK balance that is listed on fertilizers. Phosphorus is essential to a plant’s growth, but what \n"
				+ "does it mean if you have high phosphorus in your soil, or a phosphorus deficiency? Keep reading to learn more \n"
				+ "about the importance of phosphorus in plant growth. Phosphorus Deficiency in the Soil How can you tell if your\n"
				+ " garden has a phosphorus deficiency? The easiest way to tell is to look at the plants. \n"
				+ "If your plants are small, are producing little or no flowers, have weak root systems or a bright green or\n"
				+ " purplish cast, you have a phosphorus deficiency. Since most plants in the garden are grown for their flowers or fruit,\n"
				+ " replacing phosphorus in the soil if it is lacking is very important. There are many chemical fertilizers that can help you with\n"
				+ " replacing phosphorus and getting a good nutrient balance in your soil. When using chemical fertilizers, you will want to look for \n"
				+ "fertilizers that have a high “P” value (the second number in the fertilizer rating N-P-K). If you would like to correct your soil’s\n"
				+ " phosphorus deficiency using organic fertilizer, try using bone meal or rock phosphate. These both can help with replacing phosphorus in the soil.\n"
				+ " Sometimes, simply adding compost to the soil can help plants be better able to take up the phosphorus that is already in the soil, so consider\n"
				+ " trying that before you add anything else. ";
		return ph;
		}
	public String pot() {
			String n=" Potassium for crop production\r\n"
					+ "Potassium (K) is an essential nutrient for plant growth. It’s classified as a macronutrient because plants take up large quantities of K during their life cycle.\r\n"
					+ "\r\n"
					+ "Minnesota soils can supply some K for crop production, but when the supply from the soil isn’t adequate, a fertilizer program must supply the K.\r\n"
					+ "\r\n"
					+ "Here, we’ll give you a basic understanding of K, including plants’ K nutrition, how it reacts in soils, its function in plants and its role in efficient crop production. In addition, you’ll find information about soil tests, K sources, predicting potash needs and effectively applying K to your fields.\r\n"
					+ "\r\n"
					+ "Role in plant growth\r\n"
					+ "Potassium is associated with the movement of water, nutrients and carbohydrates in plant tissue. It’s involved with enzyme activation within the plant, which affects protein, starch and adenosine triphosphate (ATP) production. The production of ATP can regulate the rate of photosynthesis.\r\n"
					+ "\r\n"
					+ "Potassium also helps regulate the opening and closing of the stomata, which regulates the exchange of water vapor, oxygen and carbon dioxide. If K is deficient or not supplied in adequate amounts, it stunts plant growth and reduces yield.\r\n"
					+ "\r\n"
					+ "For perennial crops such as alfalfa, potassium plays a role in stand persistence through the winter. Other roles of K include:\r\n"
					+ "\r\n"
					+ "Increases root growth and improves drought resistance.\r\n"
					+ "\r\n"
					+ "Maintains turgor; reduces water loss and wilting.\r\n"
					+ "\r\n"
					+ "Aids in photosynthesis and food formation.\r\n"
					+ "\r\n"
					+ "Reduces respiration, preventing energy losses.\r\n"
					+ "\r\n"
					+ "Enhances translocation of sugars and starch.\r\n"
					+ "\r\n"
					+ "Produces grain rich in starch.\r\n"
					+ "\r\n"
					+ "Increases plants’ protein content.\r\n"
					+ "\r\n"
					+ "Builds cellulose and reduces lodging.\r\n"
					+ "\r\n"
					+ "Helps retard crop diseases.\r\n"
					+ "\r\n"
					+ "Potassium in soils\r\n"
					+ "The total K content of soils frequently exceeds 20,000 ppm (parts per million). While the supply of total K in soils is quite large, relatively small amounts are available for plant growth at any one time. That’s because nearly all of this K is in the structural component of soil minerals and isn’t available for plant growth.\r\n"
					+ "\r\n"
					+ "The amount of K supplied by soils varies due to large differences in soil parent materials and the effect weathering has on these materials. Therefore, the need for K in a fertilizer program varies across the United States.\r\n"
					+ "\r\n"
					+ "Three forms of K – unavailable, slowly available or fixed and readily available or exchangeable – exist in an equilibrium in the soil system. Below, we describe these forms and their relationship to one another. Figure 1 also illustrates the general relationship among these forms.\r\n"
					+ "\r\n"
					+ "Symptoms of potassium deficiency\r\n"
					+ "Some crops exhibit characteristic deficiency symptoms when adequate amounts of K aren’t available for growth and development. Potassium is mobile in plants, and will move from lower to upper leaves.Predicting potash needs\r\n"
					+ "You can monitor K status of soils with plant analysis and routine soil testing.\r\n"
					+ "\r\n"
					+ "Soil testing is the most reliable predictor of a fertilizer program’s need for potash. Plant analysis can confirm a suspected deficiency indicated by visual symptoms or routinely monitor the effects of a chosen fertilizer program.";
			return n;
			}
		public String mi() {
			String s="Iron:\r\n"
					+ "Functions – Helps in chlorophyll formation, absorption of other nutrients. Essential for the synthesis of proteins contained in the chloroplasts.\r\n"
					+ "\r\n"
					+ "Deficiency - Causes chlorosis between the veins of leaves, the veins remaining green.\r\n"
					+ "\r\n"
					+ "Manganese:\r\n"
					+ "Functions- Acts as catalyst in oxidation and reduction reactions within the plant tissues. Helps in chlorophyll formation, supports movement of iron in the plant, counteracting the bad effect of poor aeration.\r\n"
					+ "\r\n"
					+ "Deficiency- Leads to chlorosis in the inter veinal tissue of net veined leaves and parallel vein leaves. In cereals it produce grey streak, white streak dry spot and lip spot, marash spot, streak disease and pahala blight in sugarcane, yellow diseases in spinach and beans.\r\n"
					+ "\r\n"
					+ "Boron:\r\n"
					+ "Functions- It is a constituent of cell membrane and essential for cell division. Acts as a regulated of potassium/calcium ratio in the plant, helps in nitrogen absorption and translocation of sugars in plant.\r\n"
					+ "\r\n"
					+ "Deficiency- In lucerne yellows and rosetting, snakehead in walnuts, die back and corking in fruits, corking and pitting in tomatoes, hollow stem and bronzing of curd Cauliflower, brown heart disease in table beets, turnips etc.\r\n"
					+ "\r\n"
					+ "Zinc:\r\n"
					+ "Functions- Constitute of several enzyme system which regulate various metabolic reaction in the plant. Associated with water uptake and water relation in the plant.\r\n"
					+ "\r\n"
					+ "Deficiency- Deficiency symptoms appear in younger leaves starting with interveinal chlorosis leading to a reduction in shoot growth and the shorting of internodes. Mottle leaf, little leaf etc.in the case of trees, the buds of severely deficient maize plants become white, interveinal chlorosis and mottled leaf occur in citrus.\r\n"
					+ "\r\n"
					+ "Copper:\r\n"
					+ "Functions- Act as \"electron carrier\" in enzymes, helps in utilization of iron in chlorophyll synthesis. It neutralizes the harmful conditions in certain peat soils when applied in large quantity.\r\n"
					+ "\r\n"
					+ "Deficiency-Variation in deficiency symptoms occurs in case of copper e.g. multiple bud formation, staining and splitting of fruits, dieback of shoots, the marginal or spotted necrosis and cholorsis of leaves.\r\n"
					+ "\r\n"
					+ "Molybdenum:\r\n"
					+ "Functions- Acts in enzyme systems which bring about oxidation reduction reactions. Essential for the process of atmospheric nitrogen fixation.\r\n"
					+ "\r\n"
					+ "Deficiency –Reduces the activity of the symbiotic and non-symbiotic nitrogen fixing micro-organisms. Produces whiptail in cauliflower, broccoli and other Brassica crops.\r\n"
					+ "\r\n"
					+ "Chlorine:\r\n"
					+ "Functions- The exact role which, chlorine plays in plant nutrition has not yet been clearly defined. It requires for proper plant development e.g. sugarbeets, carrots, lettuce, barley, wheat, cotton and clovers. From the point of view of soil fertility, plants requires one kg of chlorine for each four thousand kg of dry matter which they produce.\r\n"
					+ "\r\n"
					+ "Deficiency- Plants display symptoms of wilt, chlorsis, necrosis, and an unusual bronze discoloration on tomatoes.";
			return s;
		}
		public String p() {
			String p="There is limited information about the factors that affect phenology of coppicing trees.\n"
					+ " This study examined the effects of water and nutrient additions on the phenology of coppicing Terminalia \n"
					+ "sericea trees in a semi-arid savanna in South Africa. Cut trees were exposed to different levels of water and \n"
					+ "nutrient (nitrogen and phosphorus) supplementations over a period of two years. Phenological stages monitored fortnightly\n"
					+ " included leaf bud presence, leaf presence and fruit production. Leaf presence followed a similar distribution to bud presence,\n"
					+ " peaking during the wet season (November–April), with the low water and high nutrient additions having \n"
					+ "the highest significant effect. Change in leaf color from the typical silvery green to yellow was delayed to\n"
					+ " later in the wet season, while higher leaf numbers were recorded during the wet seasons for trees supplemented\n"
					+ " with water and nutrients. Results indicate that the increase in water and nutrient availability has direct \n"
					+ "consequences for extending the growing season of resprouting trees. This extension has positive effects on increasing\n"
					+ " the photosynthetically active period, thus potentially increasing the carbon gain and growth of trees. \n"
					+ "Although generally low throughout the study in all treatments, fruit presence was mainly in supplemented trees.";
			return p;
		}
}
