package clg;

public class ful {
public String rose() {
String str="Rose\r\n"
		+ "Normally one-year-old budded plants having at least 3 canes on rockstocks like Rosa indica var. odorata or R.canina or R.manetti are most ideal for greenhouse cultivation.\r\n"
		+ "\r\n"
		+ "Cultivars :’Golden Gates’, ’Grand Galla’, ’First Red’, ’Kiss’, ’Konfetti’, ’Mercedez’, ’Ravel’, ’Noblesse’, ’Vivaldi’ and ’Starlite’.\r\n"
		+ "\r\n"
		+ "Planting :Optimal planting time is October-December. The planting density should be between 7-13 plants/m2 (50-60 thousand bushes/ha area). Planting should be done preferably in 2-row system.\r\n"
		+ "\r\n"
		+ "Temperature requirement : The greenhouse temperature is generally maintained from 200C or 210C on cloudy days and 240C –280C on sunny days. However, the temperature range of 15-270C is optimum.\r\n"
		+ "\r\n"
		+ "Fertiliser dose : Liquid fertilizers containing 200 ppm nitrogen and 150 ppm potassium plus iron and magnesium as needed, can be applied with good results in a wide range of soil conditions. Binding of unproductive shoots leads to more number of basal sprouts.\r\n"
		+ "\r\n"
		+ "Harvesting and yield :\r\n"
		+ "Red and pink cultivars are harvested when first 2 petals are beginning to unfold and calyx is reflexed below the horizontal lane.\r\n"
		+ "\r\n"
		+ "Yellow cultivars are harvested slightly earlier and white cultivars slightly later than red and pink types.\r\n"
		+ "\r\n"
		+ "After cutting the stem ends are dipped in 200-500 ppm citric acid or aluminium sulphate and placed in cold storage at 10C till grading. Stem ends are recut, bunched in 20’s and placed in preservative solution with sucrose up to 2%.\r\n"
		+ "\r\n"
		+ "Flower yield of 250-350 stems/m2 is considered to be ideal.\r\n"
		+ "\r\n"
		+ "Flower yield can be increased by spraying BAP 50-100 ppm before flowering flush. Burning of saw-dust during winter months in the morning hours (7-10 AM) increases flower yield and quality significantly. ";
return str;
}
public String Chrysanthemum() {
String str="Chrysanthemum\r\n"
		+ "Chrysanthemum is a very popular flower crop of commercial importance. Chrysanthemums are grown in 2 ways for cut flowers, depending upon market demand.\r\n"
		+ "\r\n"
		+ "Disbudded inflorescence : All flower buds except terminal ones are removed to allow one inflorescence/stem to develop. If the bloom is an incurved or reflexed type and in between 10 and 15 cm in diameter, is usually referred as standard.\r\n"
		+ "\r\n"
		+ "Spray inflorescence : The entire cyme is allowed to bloom but very often the central inflorescence (oldest) is removed at the time colour begins to show in the ray flowers. These groups are usually known as pompon or spray chrysanthemums.\r\n"
		+ "\r\n"
		+ "Light and temperature requirement : Chrysanthemum is primarily a typical short day plant and normally cannot form flower buds when day length exceeds 14 1/2 hr. Light and temperature are important environmental factors influencing growth and development. Chrysanthemums are broadly classified into 3 groups on the basis of their response to temperature. Thermozero varieties flower at any temperature ranging 10-270C but most consistently at a constant 160C night temperature. Thermopositive varieties require higher temperature (270C) for bud initiation and lower temperature inhibit completely. Thermonegative varieties flower at any temperature between 10 and 270C, but flowering is delayed at higher temperature.\r\n"
		+ "\r\n"
		+ "Cultivars : Selection of cultivars is very important while doing greenhouse cultivation. Spiders are preferred in the Netherlands and Germany while single spray types in Denmark, Sweden and Finland, UK and Japan prefer decorative types of mums.\r\n"
		+ "\r\n"
		+ "Most promising cultivars in the international trade are Snow Ball, Snow Don White, Mountaineer, Sonar Bangla, Bright Golden Anne, and Chandrama among large flowering types while Ajay, Birbal Sahani, Lehmans, Nanako, and Sonali Tara in case of small flowering types as sprays are most common.\r\n"
		+ "\r\n"
		+ "Planting : July-August is ideal time of planting chrysanthemum in north India. However, if controlled photroperiod facilities are available planting can be done round the year.\r\n"
		+ "\r\n"
		+ "Planting density varieties from 32 to 56 plants/m2.\r\n"
		+ "\r\n"
		+ "Practices : Pinching and disbudding are most important cultural practices for the production of quality blooms. Growth regulator spraying of B-9 (Alar) or Cycocel 2-3 blooms of good quality.\r\n"
		+ "\r\n"
		+ "Harvesting : Standard types are generally harvested when outer ray florets cease to elongate, while decorative when petals in the centre of topmost flower are fully developed. Single and anemones are harvested when flower is fully developed. ";
return str;
}

public String mari() {
String str=" Climate:\r\n"
		+ "1. Marigold requires mild climate for luxuriant growth and flowering.\r\n"
		+ "\r\n"
		+ "2. The optimum temperature range for its profuse growth is 18-20°C.\r\n"
		+ "\r\n"
		+ "3. Temperatures above 35°C restrict the growth of the plants, which leads to reduction in flower size and number.\r\n"
		+ "\r\n"
		+ "4. In severe winter, plants and flowers are damaged by frost.\r\n"
		+ "\r\n"
		+ "Soil:\r\n"
		+ "1. Marigold can be grown in a wide range of soils, as it is adapted in different soil types.\r\n"
		+ "\r\n"
		+ "2. French (Dwarf) marigolds are best cultivated in light soil whereas a rich well drained, moist soils are best suited for African (Tall) marigolds.\r\n"
		+ "\r\n"
		+ "3. Sandy loam soil with pH 5.6 to 6.5 is ideal for its cultivation.\r\n"
		+ "\r\n"
		+ "Species and cultivar\r\n"
		+ "Among 50 species of marigold only for are cultivated. These are\r\n"
		+ "\r\n"
		+ "1. Tagetes erecta (African marigold): cultivating it for medicinal, ceremonial and decorative purposes. This plant reaches heights of between 50–100 cm (20–39 in). The colour range is from white and cream to primose, yellow, gold and orange.\r\n"
		+ "\r\n"
		+ "2. Tagetes patula (French marigold): The flower is an annual, occasionally reaching 0.5 m by 0.3 m.. stem is reddish in colour and the foliage is darker than African marigold. The colour of flower varies from yellow to red, either single or double and borne on proportionately long peduncle.\r\n"
		+ "\r\n"
		+ "3. Tagetes tenufolia( Syn. T. signata); it is a dwarf and bushy plant. Flowers have 5 rays, roundish and obovate with spicy tarragon flavor.\r\n"
		+ "\r\n"
		+ "4. Tagetes lucida (sweet scented marigold): The plants are tender, perennial, leaves are sessile, small and lanceolated. Flowers are usually 2-3 rayed.Land preparation:\r\n"
		+ "For the main-field, the land should be ploughed well followed by 2-3 harrowing and mixing of FYM @ 20-25 t/ha should be incorporated to the soil. Make the ridges and furrow properly.\r\n"
		+ "\r\n"
		+ "Propagation:\r\n"
		+ "1. There are two common methods of propagation of marigold i.e. by seeds and by cuttings.\r\n"
		+ "\r\n"
		+ "2. Plants raised from seeds are tall, vigorous and heavy yielder and hence, seed propagation is preferred to cuttings.\r\n"
		+ "\r\n"
		+ "Nursery rising:\r\n"
		+ "1. The marigold seeds are black in color and remain viable for about 1-2 years for rising of seedlings,\r\n"
		+ "\r\n"
		+ "2. Seed germinate in 5-7 days. Before sowing the seeds should be treated with captan 2g/kg of seed to prevent damping off.\r\n"
		+ "\r\n"
		+ "3. Seeds should be sowed in pots, seed boxes or raised nursery beds.\r\n"
		+ "\r\n"
		+ "4. Nursery beds are prepared by digging area and incorporating well rotten FYM.\r\n"
		+ "\r\n"
		+ "5. Before sowing the seeds, the soils should be drenched with Captan to avoid the ants, which carry away the seeds.\r\n"
		+ "\r\n"
		+ "6. Seeds should be sown thinly (6-8 cm row to row) and 2cm deep and covered with sieved leaf mold.";
return str;
}

public String aster() {
String str=" Seed Germination: 8 – 10 days\r\n"
		+ "\r\n"
		+ "Plant Height: up to 24 inches\r\n"
		+ "\r\n"
		+ "Flowers Bloom: Summer and rains\r\n"
		+ "\r\n"
		+ "Colors: Blues, Purples and array of Pink\r\n"
		+ "\r\n"
		+ "How to plant aster seeds?\r\n"
		+ "Asters can be started from seed or purchased as a potted plant. When growing from seed remember that they should be planted about 1-inch deep during spring in a location that gets full to partial sunlight. Once the seeds are sown, cover them with a thin layer of soil and water thoroughly. Space the miniature varieties four to six inches apart, and giant varieties one to two feet apart. Place smaller varieties as a flower border and larger ones at the back of the flowerbed to create a lovely backdrop.How to care for Asters?\r\n"
		+ "Asters will bestow you with healthy and vibrant blooms if you feed them with compost and add general fertilizer once in a month. Mulch is an excellent option when it comes to keeping the weeds down. \r\n"
		+ "\r\n"
		+ "To maintain continuity of flowering, after each flush of bloom the faded flowers are removed, the soil is raked up, and handful of compost is added per plant.What are the diseases that affect Asters?\r\n"
		+ "Asters are prone to powdery mildew, rusts, stem cankers, white smut, leaf spots, aphids, tarsonemid, snails, and slugs. You can treat the plant at an early stage at protecting it from withering away";
return str;
}


public String gladiolus() {
String str="Bulbs prefer loam or sandy loam soil. In stiff clay, rooting is delayed and too much moisture often causes rotting. If the soil is not perfectly well-drained, the bulbs may be planted on a bed of sand. Watering is not required after planting as the fleshy underground stems contain sufficient food materials to develop initial growth of root and shoot. Before root formation, watering prove injurious to the bulbs and helps in rotting.\r\n"
		+ "\r\n"
		+ "Bulbs, corms, tubers and rhizomes are used for vegetative propagation. Various methods and structures used for propagation are as follows.\r\n"
		+ "\r\n"
		+ "Division of clump—Rhizomatous plants the Canna, Alpinia can be divided into small clumps.\r\n"
		+ "Offsets produced laterally are separated for multiplication.\r\n"
		+ "Cormlets or bulblets produce new plants.\r\n"
		+ "Scales of Lilium are separated and used for propagation.\r\n"
		+ "Pieces of bulb disc with leaves or rhizome also develop new plan\r\n"
		+ "Bulbil arising from the axils of leaves can produce new plants.\r\n"
		+ "Bulbous plants are grown in beds, shrubbery, herbaceous border, grassy land and in pots and bowl. Bulbs, corms, rhizome or tuber are usually planted when they have shown signs of sprouting after dormancy.\r\n"
		+ "\r\n"
		+ "The planting materials are normally placed deep in the soil and the soil around it is gently pressed. The depth of planting varies with the type or plants and size of bulbs. For most of the bulbous plants grown in tropical garden, the planting depth is between 3-10 cm.\r\n"
		+ "\r\n"
		+ "Most of these plants sunny situation, while Eucharis, Zephyranthes thrive better in semishade; few types, e.g. Pancratium, Haemanthus, Zephyranthes grow and flower well in sun and semishade. Bulbs, corms and tubers should not come in direct contact with fresh organic manure, rhizomes are not usually affected. Time of planting depends on the season of flowering, environmental condition of the region and condition of the planting material. In the plains, Gladiolus is planted from September to November, whereas in the hills, the planting season is normally from April-June. Amaryllis, Hippeastrum, Haemanthus are planted in January-February to obtain flowers in March-April. Caladium and Canna are put in the ground in May.\r\n"
		+ "\r\n"
		+ "After the above ground portion dries out the bulbs are lifted out carefully. The root and shoot are cut and the bulbs are cleaned before storage. They should be stored in dark, dry and airy place until the time of next planting. Storage condition is very important for obtaining healthy bulbs. If the humidity is very high, fungus develops on the bulbs and causes rotting. In a very dry atmosphere the bulbs shrived and may lose viability. ";
return str;
}
public String mogra() {
String str="Logo\r\n"
		+ "Toggle navigation\r\n"
		+ "EVERYTHING ABOUT GROWING MOGRA (ARABIAN JASMINE) PLANT\r\n"
		+ "Ornamental Gardening\r\n"
		+ "jasmine flower\r\n"
		+ "About Mogra plant:\r\n"
		+ "Mogra plant is dwarf growing shrub with almost stalkless leaves and wavy margins. The plant can be grown as a short climber too. The heavy scented white flowers are borne in clusters of 3 to 12 and may be single, semi-double or perfectly double. The plant flowers mainly in the summer and rainy seasons, but several other flushes during other parts of the year are quite common.\r\n"
		+ "\r\n"
		+ "Different names of Mogra:\r\n"
		+ "The scientific name of Mogra is Jasminum sambac; it belongs to family Oleaceae. Although native to India, it is commonly known as Arabian Jasmine. It is the double flowering types that are known as Motiya or Mogra in India. The large double flowers (Tuscan) are known by different names like Boddu malle, rai; the semi-doubles are known as dondhara malle, moturia etc.\r\n"
		+ "\r\n"
		+ "Important Mogra Varieties: Motia, Single Mohora, Double Mohora, Khoya, Rai Japanese, Iruvatchi, Madanban, Ramabanam, Suji mallige etc.\r\n"
		+ "\r\n"
		+ "mogra plant\r\n"
		+ "\r\n"
		+ "Propagation of Mogra plant:\r\n"
		+ "Mogra is propagated by stem cuttings of almost mature wood of old plant. The cuttings are raised in nursery beds and planted in pots after one year. The plant can also be propagated by layering, commonly ground layering. The best time for propagation by either method is the rainy season. Plants can easily be grown by root division at the time of re-potting. Seeds are rarely used for propagation.\r\n"
		+ "\r\n"
		+ "Planting Mogra:\r\n"
		+ "Once planted Mogra plant will remain in the field for 10 to 15 years. This makes it obligatory to plough the land deeply and prepare it thoroughly by ploughing and harrowing. The best time for planting in most parts of India is a monsoon. On the ground, Mogra is planted 75 cm apart in rows spaced 1 m apart.\r\n"
		+ "\r\n"
		+ "Growing Mogra plant in a container:\r\n"
		+ "Type of pot: A regular round pot of 12-inch size is ideal for growing Mogra plant. Traditionally plant is grown in an earthen pot. However, hardy plastic pots are also suitable.\r\n"
		+ "\r\n"
		+ "Click here to buy plastic pots online in India.\r\n"
		+ "\r\n"
		+ "Potting soil: Mogra plant requires well-drained soil with plenty of organic matter. Two parts of loam soil and one part well-decomposed cow manure makes an ideal potting mixture. You can buy premium garden soil mix at Ugaoo.com\r\n"
		+ "\r\n"
		+ "Sunlight: The plant requires full sunlight for best blooming. Mogra plant can also thrive very well in partial shade, which makes it a perfect plant for windowsill gardening.\r\n"
		+ "\r\n"
		+ "arabian jasmine plant\r\n"
		+ "\r\n"
		+ "Schedule of gardening practices for Mogra plant:\r\n"
		+ "Watering: Moderate Watering is good for Mogra plant. It is essential in the flowering season. Mogra cannot withstand water logging and plants will be killed in the waterlogged soil in no time. Watering is stopped during November to enable the plants to rest.\r\n"
		+ "\r\n"
		+ "Defoliation: Once the watering is stopped, the plants shed the leaves. If it does not happen, all the leaves on the plant should be removed by hand.\r\n"
		+ "\r\n"
		+ "Pruning: Defoliation is followed by a light pruning of stems. Branches are pruned one-third of their length.Harvesting Mogra flowers:\r\n"
		+ "The plant begins to flower second year onwards after planting. The flowers are harvested in bud stage either in the evening or early in the morning by handpicking.\r\n"
		+ "\r\n"
		+ "Flower buds are used for garland making, adorning hair, worshipping, decoration, and extraction of perfume. ";
return str;
}
public String jasmine() {
String str="Scientific name: Jasminum spp.\r\n"
		+ "Local name : Jasmine\r\n"
		+ "Hindi name : Juhi, Chameli, Mogra, Champa Bela etc.\r\n"
		+ "Family: Oleaceae\r\n"
		+ "\r\n"
		+ "Origin\r\n"
		+ "Jasmines are native of tropical and subtropical regions and introduced in the mid sixteenth century. Among the large number of species existing, only three species have attained importance in commercial cultivation. Jasminum sambac is considered as a native of the East Indies. The name Jasmine is of Arabic origin and is believed to have been derived from Yasmin. It is reported that the height of its po pularity reached its peck two to five hundred years ago at canton and metropolis of southern China.\r\n"
		+ "\r\n"
		+ "Area under cultivation in India\r\n"
		+ "In India, jasmines are cultivated throughout the country but the commercial cultivation is confined to Coimbatore, Madurai, and Dindigul (Tamil Nadu); Bangalore, Bellary, Mysore and Kolar (Karnataka); Knnauj, Jaunpur and Gazipur (Utter Pradesh); Udaipur, Jaipur, Ajmer and Kota (Rajasthan); Ranaghat, Kolaghat, Pancskura (West Bengal); parts of Andhra Pradesh and Maharashtra.\r\n"
		+ "\r\n"
		+ "Major types\r\n"
		+ "Jasminum auriculatum - Mullai\r\n"
		+ "Jasminum grandiflorum - Jathimalli (or) Pitchi (or) Spanish jasmine\r\n"
		+ "Jasminum sambac - Gundumalli / Malligai / Arabian jasmine /Tuscan jasmine\r\n"
		+ "Jasminum pubescens - Kakada\r\n"
		+ "mullaijathimullaigundumallikakada\r\n"
		+ "Soil and climate\r\n"
		+ "Jasmine can be grown on a wide range of soils. Well-drained, rich loamy soil with a pH ranging from 6.5-7.5 is ideal for their cultivation.\r\n"
		+ "\r\n"
		+ "Jasmine prefers mild and tropical climate. Jasmine isLayering : Layering is done during June-July in North India and from June to December in South India. For preparation of layers, well matured, one year old shoots are selected and are buried in the soil 10-15 cm deep after making a shallow, slanting cut in the portion that is to be buried. The root formation occurs in 90-120 days.\r\n"
		+ "\r\n"
		+ "Cutting : It is the easiest method of propagation of jasmine J.grandiflorum and J.sambac are best propagated by apical cuttings while J.auriculatum is propagated by semi hardwood cuttings. Normally 22-25 cm long cuttings with 3-4 nodes are planted in rooting media. Cuttings taken during April-September has highest percentage of rooting with maximum rooting in June planted cuttings. The basal portion of softwood cuttings is treated with growth regulating substances (IBA 400ppm and IAA @ 1000ppm) before planting. The cuttings are buried more than 5 cm deep in the rooting medium and are spaced 7cm apart. The cuttings are ready for transplanting into the main field after 4 to 5 months of planting in the rooting media.\r\n"
		+ "\r\n"
		+ "Planting\r\n"
		+ "Season of Planting : The best time for planting in most parts of India is during the monsoon but one can plant jasmine almost round the year in climates as of Bangalore. Once planted, the jasmine remains in the field for 10-15 years.The ideal time for planting in North India is during July-August and from the end of January-February, while in South India planting is done any time between July-December.\r\n"
		+ "\r\n"
		+ "Spacing : TNAU, Coimbatore has recommended a planting distance of 1.5 x 1.5m for J. auriculatum and J. sambac and a spacing of 2.0 x 1.5m for J. grandiflorum.\r\n"
		+ "\r\n"
		+ "Pit Digging : The soil is well pulverized and weeds are removed before planting. Pits of 45 cm3 are prepared one month before planting and are exposed to sunlight. A few days before planting, pits are filled with FYM, fresh soil and coarse sand in the ratio of 2:1:1. Addition of BHC (10g/pit) to the soil in the pit helps to prevent the attack of termites. Pits are watered to settle the soil compost mixture.\r\n"
		+ "\r\n"
		+ "Method of Planting : Well-rooted, healthy and strong seedlings obtained from cutting/layering are planted in each pit. The best time for planting in most parts of India is dur ing the monsoon but one can plant jasmine almost round the year in climates as of Bangalore. Once planted, the jasmine remains in the field for 10 - 15 years. A hole is dug in the centre of the pit sufficient enough to accommodate the soil ball of the seedling. The soil ball is placed in the centre of the pit and the soil is firmly pressed around the seedlings. The plantWeeding - Weed growth within the jasmine crop competes with the main crop for nutrients. Therefore it is essential to remove the weeds at the appropriate time. After pruning, the soil 15-30 cm from the main stem around the bushes is stirred to a depth of 15 cm. This should be repeated every two to three months. Though manual weed control is effective, but it is very expensive. Mulching also reduces the weed population considerably. Chemical weed control is comparatively economical, convenient and efficient in eradicating weeds with one or two applications.\r\n"
		+ "\r\n"
		+ "Intercropping - In the initial years when there is sufficient space between the plants, vegetable crops and ornamental plants can be grown as intercrop.\r\n"
		+ "\r\n"
		+ "Pruning - Pruning is an important activity as it influences growth, flower-bud initiation, differentiation and, ultimately, the flower production in Jasmine. Usually, irrigation is stopped before pruning and plants are pruned to half their original length. All the leaves are stripped off after pruning. All the cut ends are smeared with Bordeaux paste to prevent entry of pathogens. Pruning is done at 45cm from the ground level. Pruning done during mid of December to mid January results in maximum number of branches and higher yield of flowers.\r\n"
		+ "\r\n"
		+ "Harvesting\r\n"
		+ "Jasmine gives economic yield only from the third year and up to 12 - 15 years and then the yield starts declining. The stage of harvest depends on the purpose of flowers to be harvested. For fresh flowers, fully developed unopened flower buds are picked in the early morning, while for extraction of concrete only fully opened fresh picked flowers are required. Picking of flowers after 11 a.m. will considerably reduce the yield and quality of the concrete. Damage to flowers during harvest and transit will affect shelf life of fresh flowers and concrete recovery. commercially grown in India under open field conditions. The ideal requirements for successful cultivation of jasmine are mild winter, warm summer, moderate rainfall and sunny days. Jasmines grow well upto 1200 m. ";
return str;
}

}
